export const news = [{
    "status": "ok",
    "total_hits": 10000,
    "page": 1,
    "total_pages": 200,
    "page_size": 50,
    "articles": [
        {
            "title": "College of Engineering adds 15 faculty members",
            "author": null,
            "published_date": "2022-03-25 20:32:05",
            "published_date_precision": "full",
            "link": "https://www.psu.edu/news/engineering/story/college-engineering-adds-15-faculty-members",
            "clean_url": "psu.edu",
            "excerpt": "The Penn State College of Engineering has added 15 faculty members this semester, with 11 tenured or tenure-line members and four non-tenure-line members.",
            "summary": "UNIVERSITY PARK, Pa. — The Penn State College of Engineering has added 15 faculty members this semester, with 11 tenured or tenure-line members and four non-tenure-line members.\n\n'It is my pleasure to welcome our newest faculty members, who demonstrate breadth of experience and depth of expertise from a wide variety of focuses across engineering, to the college,' said Justin Schwartz, Harold and Inge Marcus Dean in the College of Engineering. 'They represent the most recent growth of 12 departments and student support services in the college — a trend we will continue to drive to advance our position at the leading edge of engineering research and education.",
            "rights": "psu.edu",
            "rank": 304,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://psu-gatsby-files-prod.s3.amazonaws.com/s3fs-public/styles/16_9_1000w/public/2022/03/new%20faculty-psn-1.jpg?h=652e55f1&itok=p-2EnaaX",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 11.716475,
            "_id": "1d56ad4885f142b83e3cc9e91c7a2ee4"
        },
        {
            "title": "Eleven alumni to receive College of Engineering's highest honor",
            "author": null,
            "published_date": "2022-03-29 20:15:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.psu.edu/news/engineering/story/eleven-alumni-receive-college-engineerings-highest-honor",
            "clean_url": "psu.edu",
            "excerpt": "UNIVERSITY PARK, Pa. — Eleven Penn State engineering graduates will be honored on April 4 at the College of Engineering's Outstanding Engineering Alumni Awards ceremony at Hyatt Place State College.…",
            "summary": "UNIVERSITY PARK, Pa. — Eleven Penn State engineering graduates will be honored on April 4 at the College of Engineering's Outstanding Engineering Alumni Awards ceremony at Hyatt Place State College. Charlie Blenko, an undergraduate student majoring in civil engineering, will serve as the event's emcee. \nEstablished in 1966, the Outstanding Engineering Alumni Award is the highest honor bestowed by the College of Engineering and recognizes graduates who have reached exceptional levels of professional achievement.",
            "rights": "psu.edu",
            "rank": 304,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://behrend.psu.edu/sites/behrend/files/styles/teaser_thumbnail/public/oea22-ps-news20copy.jpg?itok=0T2kehom",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 11.4320545,
            "_id": "89667085cd89c6fd402441319bab176a"
        },
        {
            "title": "Seed Engineering Services Market 2022:Key market Insights, Drivers and Restraints, Opportunities and Challenges, Sales and Revenue and Forecast Period 2022-2028",
            "author": "Qy Research",
            "published_date": "2022-03-29 04:53:21",
            "published_date_precision": "timezone unknown",
            "link": "https://www.openpr.com/news/2589244/seed-engineering-services-market-2022-key-market-insights",
            "clean_url": "openpr.com",
            "excerpt": "Los Angeles, United States: The global Seed Engineering Services market is carefully researched in the report while largely concentrating on top players and their business tactics, geographical expansion, market segments, competitive landscape, manufacturing, and pricing and cost structures. Each section",
            "summary": "Seed Engineering Services Market 2022:Key market Insights, Drivers and Restraints, Opportunities and Challenges, Sales and Revenue and Forecast Period 2022-2028|Seed Engineering ,AGI ,Seed Consulting\n\nhttps://www.qyresearch.com/sample-form/form/4458949/global-seed-engineering-services-market\n\nhttps://www.qyresearch.com/settlement/pre/3779de9eb37a466f8576e718c7299eb8,0,1,global-seed-engineering-services-market\n\nhttp://www.qyresearch.com\n\nLos Angeles, United States: The global Seed Engineering Services market is carefully researched in the report while largely concentrating on top players and their business tactics, geographical expansion, market segments, competitive landscape, manufacturing, and pricing and cost structures.",
            "rights": "openpr.com",
            "rank": 14600,
            "topic": "business",
            "country": "DE",
            "language": "en",
            "authors": [
                "Qy Research"
            ],
            "media": "https://cdn.openpr.com/V/3/V329113192_g.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 11.4293375,
            "_id": "362dc66fd9b7dd3086900998d50c88ad"
        },
        {
            "title": "How COVID upended engineering — and created new opportunities for progress on public health",
            "author": "Theresa Anne Salah",
            "published_date": "2022-03-25 11:30:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.dal.ca/news/2022/03/25/covid-engineering-health.html",
            "clean_url": "dal.ca",
            "excerpt": "As the world continues to navigate its way out of a deadly health crisis, Dalhousie's Women in Engineering Society hosts a panel discussion next week on how the crisis has strengthened the…",
            "summary": "Although some people may not realize it, engineering impacts every aspect of our lives. From the keyboard you type on to the water you drink, each sector of our society requires the expertise of an engineer.\nThat's why when the world was upended suddenly by the COVID-19 pandemic, so, too, was engineering.\n\n'While the pandemic has been incredibly challenging for us all, I think it has also led to new opportunities,' says Amina Stoddart, an assistant professor in Dalhousie's Department of Civil and Resource Engineering.",
            "rights": "dal.ca",
            "rank": 3075,
            "topic": "news",
            "country": "CA",
            "language": "en",
            "authors": [
                "Theresa Anne Salah"
            ],
            "media": "https://cdn.dal.ca/news/2022/03/25/covid-engineering-health/_jcr_content/image.adaptive.full.high.jpg/1648155880449.jpg",
            "is_opinion": false,
            "twitter_account": "@Dalnews",
            "_score": 11.378005,
            "_id": "48a0776be6e16472ff35456bb8513b7c"
        },
        {
            "title": "Bio-based Engineering Plastics Market Trends 2022, In-Depth Analysis of Industry Growth and Forecast Up To 2028",
            "author": "Qyresearch Inc.",
            "published_date": "2022-03-29 19:06:45",
            "published_date_precision": "timezone unknown",
            "link": "https://www.openpr.com/news/2590340/bio-based-engineering-plastics-market-trends-2022-in-depth",
            "clean_url": "openpr.com",
            "excerpt": "\"Market Summary\nA newly published report titled \"Bio-based Engineering Plastics Market\" by QY Research throws light on the industry dynamics and current and future trends that play a key role in determining the business expansion. The report also highlights the key",
            "summary": "Bio-based Engineering Plastics Market Trends 2022, In-Depth Analysis of Industry Growth and Forecast Up To 2028 | Mitsubishi Chemical Corporation, DSM Engineering Plastics, König & Meyer\n\nhttps://www.qyresearch.com/sample-form/form/4410240/global-bio-based-engineering-plastics-market\n\nhttps://www.qyresearch.com/customize-request/form/4410240/global-bio-based-engineering-plastics-market\n\nhttps://www.qyresearch.com/settlement/pre/4410240/global-bio-based-engineering-plastics-market\n\nwww.qyresearch.",
            "rights": "openpr.com",
            "rank": 14600,
            "topic": "business",
            "country": "DE",
            "language": "en",
            "authors": [
                "Qyresearch Inc."
            ],
            "media": "https://cdn.openpr.com/V/3/V329498331_g.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 11.32544,
            "_id": "65ffdc6753ddbe7fa66989c5692ed350"
        },
        {
            "title": "INTERACT: The most progressive, diverse conference for engineering leaders",
            "author": "LinearB",
            "published_date": "2022-03-29 09:00:00",
            "published_date_precision": "full",
            "link": "https://www.newswire.ca/news-releases/interact-the-most-progressive-diverse-conference-for-engineering-leaders-881569330.html",
            "clean_url": "newswire.ca",
            "excerpt": "/CNW/ -- INTERACT, the community-driven conference for engineering leaders, is back for its second year. Featuring more than 50% female and minority speakers,...",
            "summary": "The popular community-driven engineering leadership conference returns on April 7th \nSEATTLE, March 29, 2022 /CNW/ -- INTERACT, the community-driven conference for engineering leaders, is back for its second year. Featuring more than 50% female and minority speakers, INTERACT, hosted by LinearB, highlights some of the biggest names in engineering leadership, with speakers from Netflix, Slack, Stack Overflow, American Express, and more on April 7, 2022.\nINTERACT's free half-day virtual conference will host more than 1,500 engineering leaders from 75 different countries, features prominent influencers in software engineering, and has committed to accessibility measures including live captioning.",
            "rights": "newswire.ca",
            "rank": 2301,
            "topic": "news",
            "country": "CA",
            "language": "en",
            "authors": [
                "LinearB"
            ],
            "media": "https://mma.prnewswire.com/media/1775086/Screen_Shot_2022_03_28_Logo.jpg?p=facebook",
            "is_opinion": false,
            "twitter_account": "@PRNewswire",
            "_score": 11.270802,
            "_id": "5a85b433a78750457015bdf0d22cd755"
        },
        {
            "title": "Plant Engineering Software Market Share Insights 2022, Industry On-Going Trends, Covid-19 Impact Analysis, Segmentation Analysis by Type, Application, Regions and Countries, Historical Data and Forecast (2022-2026)",
            "author": "TheExpressWire",
            "published_date": "2022-03-30 06:35:08",
            "published_date_precision": "full",
            "link": "https://www.digitaljournal.com/pr/plant-engineering-software-market-share-insights-2022-industry-on-going-trends-covid-19-impact-analysis-segmentation-analysis-by-type-application-regions-and-countries-historical-data-and-foreca",
            "clean_url": "digitaljournal.com",
            "excerpt": "Global Plant Engineering Software Market research report 2021 is detailed businesses think about on the present state of industry which studies innovative strategies for business growing and defines…",
            "summary": "Global Plant Engineering Software Market research report 2021 is detailed businesses think about on the present state of industry which studies innovative strategies for business growing and defines important factors such as top players, manufacture value, key regions, growth rate, suppliers, SWOT analysis i.e. strength, weakness, opportunities and threat to the organization and others.\n\n'Final Report will add the analysis of the impact of COVID-19 on this industry.'\nThe report on the 'Plant Engineering Software Market' covers the current status of the market including Plant Engineering Software market size, growth rate, recent developments, prominent players, market dynamics, and current competitive landscape.",
            "rights": "digitaljournal.com",
            "rank": 1610,
            "topic": "economics",
            "country": "CA",
            "language": "en",
            "authors": [
                "Dr. Tim Sandle",
                "Written By"
            ],
            "media": "https://secure.gravatar.com/avatar/a5936643cfb93345023945704b62c134?s=150&d=blank&r=pg",
            "is_opinion": false,
            "twitter_account": "@digitaljournal",
            "_score": 11.258476,
            "_id": "7300dafd45b61ba0d9492ee458685f1e"
        },
        {
            "title": "INTERACT: The most progressive, diverse conference for engineering leaders",
            "author": "LinearB",
            "published_date": "2022-03-29 09:00:00",
            "published_date_precision": "full",
            "link": "https://www.prnewswire.com/news-releases/interact-the-most-progressive-diverse-conference-for-engineering-leaders-301512240.html",
            "clean_url": "prnewswire.com",
            "excerpt": "/PRNewswire/ -- INTERACT, the community-driven conference for engineering leaders, is back for its second year. Featuring more than 50% female and minority...",
            "summary": "The popular community-driven engineering leadership conference returns on April 7th \nSEATTLE, March 29, 2022 /PRNewswire/ -- INTERACT, the community-driven conference for engineering leaders, is back for its second year. Featuring more than 50% female and minority speakers, INTERACT, hosted by LinearB, highlights some of the biggest names in engineering leadership, with speakers from Netflix, Slack, Stack Overflow, American Express, and more on April 7, 2022.\nINTERACT's free half-day virtual conference will host more than 1,500 engineering leaders from 75 different countries, features prominent influencers in software engineering, and has committed to accessibility measures including live captioning.",
            "rights": "prnewswire.com",
            "rank": 216,
            "topic": "business",
            "country": "US",
            "language": "en",
            "authors": [
                "LinearB"
            ],
            "media": "https://mma.prnewswire.com/media/1775086/Screen_Shot_2022_03_28_Logo.jpg?p=facebook",
            "is_opinion": false,
            "twitter_account": "@PRNewswire",
            "_score": 11.254728,
            "_id": "6c3ee37ffbc7807c55b577c9ac618c48"
        },
        {
            "title": "Accept challenges boldly, graduates told",
            "author": "https://tribune.com.pk/author/440",
            "published_date": "2022-03-28 06:05:05",
            "published_date_precision": "full",
            "link": "https://tribune.com.pk/story/2349977/accept-challenges-boldly-graduates-told",
            "clean_url": "tribune.com.pk",
            "excerpt": "Over 1,100 students conferred degrees at varsity's silver jubilee passing out",
            "summary": "KARACHI:\n\nSir Syed University of Engineering & Technology (SSUET), organized its 25th Convocation with traditional zeal that was attended by a large number of educationists, scholars, dignitaries including faculty and students.\nRenowned Businessman Bashir Jan Muhammad was the chief guest of the event. On this memorable occasion around more than 1100 degrees were awarded to the pass-outs of BS and MS programme. Position holders were awarded with gold, silver and bronze medals for securing highest marks in the respective disciplines.",
            "rights": "tribune.com.pk",
            "rank": 4304,
            "topic": "news",
            "country": "PK",
            "language": "en",
            "authors": [
                "https://tribune.com.pk/author/440"
            ],
            "media": "https://i.tribune.com.pk/media/images/684405-graduatereutersxcopy-1395163923/684405-graduatereutersxcopy-1395163923.jpg",
            "is_opinion": false,
            "twitter_account": "@etribune",
            "_score": 11.2429495,
            "_id": "bbaf99078009ca7b06a0d585d8619340"
        },
        {
            "title": "Estimation of Parameters of Different Equivalent Circuit Models of Solar Cells and Various Photovoltaic Modules Using Hybrid Variants of Honey Badger Algorithm and Artificial Gorilla Troops Optimizer",
            "author": "Aleem",
            "published_date": "2022-03-25 00:00:00",
            "published_date_precision": "date",
            "link": "https://www.mdpi.com/2227-7390/10/7/1057",
            "clean_url": "mdpi.com",
            "excerpt": "Parameters of the solar cell equivalent circuit models have a significant role in assessing the solar cells' performance and tracking operational variations. In this regard, estimating solar cell…",
            "summary": "This is an early access version, the complete PDF, HTML, and XML versions will be available soon.\n\n\nOpen AccessArticle by\n 1,2, 1,2, 1,2, 3, 3, 4,5,*, 1,6, 1,7, 1,2 and 8 \n\n\n1\nCenter of Research Excellence in Renewable Energy and Power Systems, King Abdulaziz University, Jeddah 21589, Saudi Arabia\n\n\n2\nDepartment of Electrical and Computer Engineering, Faculty of Engineering, King Abdulaziz University, Jeddah 21589, Saudi Arabia\n\n\n3\nFaculty of Electrical Engineering, University of Montenegro, 8100",
            "rights": "Creative Commons Attribution (CC-BY)",
            "rank": 668,
            "topic": "science",
            "country": "CH",
            "language": "en",
            "authors": [
                "Rawa",
                "Abusorrah",
                "Al-Turki",
                "Calasan",
                "Micev",
                "Ali",
                "Mekhilef",
                "Bassi",
                "Sindi",
                "Aleem"
            ],
            "media": "https://www.mdpi.com/img/journals/mathematics-logo-sq.png?4c4bd2c818fd7d64",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 11.235029,
            "_id": "840761a746acab8734fec1483c64b4bb"
        },
        {
            "title": "Electric Vehicle Engineering Plastics Market to Register Steady Growth During 2028",
            "author": "Transparency Market Research",
            "published_date": "2022-03-28 18:30:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.digitaljournal.com/pr/electric-vehicle-engineering-plastics-market-to-register-steady-growth-during-2028",
            "clean_url": "digitaljournal.com",
            "excerpt": "Electric Vehicle Engineering Plastics Market: Introduction Transparency Market Research delivers key insights on the global electric vehicle engineering plastics market. In terms of revenue, the…",
            "summary": "Electric Vehicle Engineering Plastics Market: Introduction\nTransparency Market Research delivers key insights on the global electric vehicle engineering plastics market. In terms of revenue, the global electric vehicle engineering plastics market is estimated to expand at a CAGR of 27.3% during the forecast period, owing to numerous factors, regarding which TMR offers thorough insights and forecast in its report on the global electric vehicle engineering plastics market.\nThe global electric vehicle engineering plastics market is broadly affected by several factors, including increase in usage of electric vehicle engineering plastics in various components such as interior trim, exterior trim, and electronic components.",
            "rights": "digitaljournal.com",
            "rank": 1610,
            "topic": "news",
            "country": "CA",
            "language": "en",
            "authors": [
                "Transparency Market Research",
                "Karen Graham",
                "Written By"
            ],
            "media": "https://secure.gravatar.com/avatar/ca62a7dacc3c89e59e508308ec6fe403?s=150&d=blank&r=pg",
            "is_opinion": false,
            "twitter_account": "@digitaljournal",
            "_score": 11.2280855,
            "_id": "a6a05baf03d57b667c5a32813f2262af"
        },
        {
            "title": "Hydro One celebrates recipients of Women in Engineering Scholarship",
            "author": "Hydro One Inc.",
            "published_date": "2022-03-29 11:00:00",
            "published_date_precision": "full",
            "link": "https://www.newswire.ca/news-releases/hydro-one-celebrates-recipients-of-women-in-engineering-scholarship-807504094.html",
            "clean_url": "newswire.ca",
            "excerpt": "/CNW/ - Today, Hydro One announced the recipients of its Women in Engineering Scholarship, who will each receive $5,000 and an opportunity to complete a paid...",
            "summary": "\"Hydro One is committed to creating a workforce that is reflective of the diverse populations of the communities where we live and work,\" said Megan Telford, Chief Human Resources Officer, Hydro One. \"As a company, we are taking real action to hire and retain more gender diverse teammates, with a focus on trades and other traditionally male-dominated positions. Congratulations to the Women in Engineering Scholarship recipients as they pursue careers in engineering and the electricity industry.\"",
            "rights": "newswire.ca",
            "rank": 2301,
            "topic": "news",
            "country": "CA",
            "language": "en",
            "authors": [
                "Hydro One Inc."
            ],
            "media": "https://mma.prnewswire.com/media/1775651/Hydro_One_Inc__Hydro_One_celebrates_recipients_of_Women_in_Engin.jpg?p=facebook",
            "is_opinion": false,
            "twitter_account": "@PRNewswire",
            "_score": 11.21583,
            "_id": "303bf6bd4861cad9c459d91f03ddd14d"
        },
        {
            "title": "INTERACT: The most progressive, diverse conference for engineering leaders",
            "author": "LinearB",
            "published_date": "2022-03-29 09:00:00",
            "published_date_precision": "full",
            "link": "https://www.prnewswire.co.uk/news-releases/interact-the-most-progressive-diverse-conference-for-engineering-leaders-826241772.html",
            "clean_url": "prnewswire.co.uk",
            "excerpt": "/PRNewswire/ -- INTERACT, the community-driven conference for engineering leaders, is back for its second year. Featuring more than 50% female and minority...",
            "summary": "The popular community-driven engineering leadership conference returns on April 7th \nSEATTLE, March 29, 2022 /PRNewswire/ -- INTERACT, the community-driven conference for engineering leaders, is back for its second year. Featuring more than 50% female and minority speakers, INTERACT, hosted by LinearB, highlights some of the biggest names in engineering leadership, with speakers from Netflix, Slack, Stack Overflow, American Express, and more on April 7, 2022.\nINTERACT's free half-day virtual conference will host more than 1,500 engineering leaders from 75 different countries, features prominent influencers in software engineering, and has committed to accessibility measures including live captioning.",
            "rights": "prnewswire.co.uk",
            "rank": 7424,
            "topic": "news",
            "country": "GB",
            "language": "en",
            "authors": [
                "LinearB"
            ],
            "media": "https://mma.prnewswire.com/media/1775086/Screen_Shot_2022_03_28_Logo.jpg?p=facebook",
            "is_opinion": false,
            "twitter_account": "@PRNewswire",
            "_score": 11.19587,
            "_id": "d13c9947a7afd95d784d18fb3f62c395"
        },
        {
            "title": "Development of a Modular Software Architecture for Underwater Vehicles Using Systems Engineering",
            "author": "Rafael E. Vásquez",
            "published_date": "2022-03-25 00:00:00",
            "published_date_precision": "date",
            "link": "https://www.mdpi.com/2077-1312/10/4/464",
            "clean_url": "mdpi.com",
            "excerpt": "This paper addresses the development of a modular software architecture for the design/construction/operation of a remotely operated vehicle (ROV), based on systems engineering. First, systems…",
            "summary": "Open AccessFeature PaperArticle by\n 1, 1, 2, 1, 1 and 1,* \n\n\n1\nSchool of Engineering, Universidad Pontificia Bolivariana, Medellín 050031, Colombia\n\n\n2\nElectronics and Telecommunications Engineering Department, Universidad de Medellín, Medellín 050026, Colombia\n\n\n*\nAuthor to whom correspondence should be addressed. \n\n\n\nAcademic Editors: Angelo Odetti, Gabriele Bruzzone and Roberta Ferretti\n\nJ. Mar. Sci. Eng. 2022, 10(4), 464; https://doi.org/10.3390/jmse10040464 (registering DOI)\n\n\nReceived: 28 February 2022\n/\nRevised: 15 March 2022\n/\nAccepted: 22 March 2022\n/\nPublished: 25 March 2022\n\n\n(This article belongs to the Special Issue Unmanned Marine Vehicles II)\n \n\nThis paper addresses the development of a modular software architecture for the design/construction/operation of a remotely operated vehicle (ROV), based on systems engineering.",
            "rights": "Creative Commons Attribution (CC-BY)",
            "rank": 668,
            "topic": "science",
            "country": "CH",
            "language": "en",
            "authors": [
                "Carlos A. Zuluaga",
                "Luis M. Aristizábal",
                "Santiago Rúa",
                "Diego A. Franco",
                "Dorie A. Osorio",
                "Rafael E. Vásquez"
            ],
            "media": "https://www.mdpi.com/jmse/jmse-10-00464/article_deploy/html/images/jmse-10-00464-g001-550.jpg",
            "is_opinion": false,
            "twitter_account": "@MDPIOpenAccess",
            "_score": 11.173075,
            "_id": "a51263bc4445c24fcb3f22d2aa2629b6"
        },
        {
            "title": "Report charts path to attracting more Australian women into engineering careers",
            "author": "Sarah Lansdown",
            "published_date": "2022-03-27 18:30:00",
            "published_date_precision": "full",
            "link": "https://www.canberratimes.com.au/story/7672128/most-people-dont-really-know-what-engineers-do-now-you-can-find-out",
            "clean_url": "canberratimes.com.au",
            "excerpt": "A new report calls for schools, government and industry to make a renewed effort to entice women and girls to become engineers.",
            "summary": "Every minute of the day people are interacting with the work of engineers. From the computers we use, to transportation and infrastructure around us, engineers have solved problems we face in everyday life.But most people don't know what engineers do, and it's this image problem that is stopping young people, especially women, from joining the profession.Engineers Australia chief engineer Jane MacMaster said it was frustrating that women still only make up 12 per cent of working engineers.\"I studied mechanical engineering 30 years ago and the dial has not shifted in any measurable amount in mechanical engineering in particular, and that's three decades.",
            "rights": "theflindersnews.com.au",
            "rank": 5743,
            "topic": "news",
            "country": "AU",
            "language": "en",
            "authors": [
                "Sarah Lansdown"
            ],
            "media": "https://www.theflindersnews.com.au/images/transform/v1/crop/frm/33pRA5ArzT57tWtt8VHHenS/4eb9e3b2-e47e-4a3c-838f-8555dc902d17.jpg/r14_0_5676_3199_w1200_h678_fmax.jpg",
            "is_opinion": false,
            "twitter_account": "@TheFlindersNews",
            "_score": 11.168878,
            "_id": "2c6b2a78e5b8ed1b1566a3c23f85f3d4"
        },
        {
            "title": "Engineering Outlook 2022: Computer science top preference among Engineering aspirants",
            "author": "Republic World",
            "published_date": "2022-03-27 16:51:00",
            "published_date_precision": "full",
            "link": "https://www.republicworld.com/education/news/engineering-outlook-2022-computer-science-top-preference-among-engineering-aspirants-articleshow.html",
            "clean_url": "republicworld.com",
            "excerpt": "Engineering Outlook 2022: It has come to the fore that a maximum number of students have an inclination towards pursuing a career in computer science, (CS).",
            "summary": "Engineering Outlook 2022: It has come to the fore that a maximum number of students have an inclination towards pursuing a career in computer science or CS. According to a report by InfoEdge (India) Ltd.'s Shiksha.com, after the COVID-19 pandemic arrived, there has been a large variant in the shift in engineering applicants' preferences and choices. Students are now mainly focused on appearing for admission exams rather than entrance exams, leading to a dip in the number of entrance tests. Notably, students are now choosing to study in their native places rather than going to metro cities to avoid the problems they faced during the lockdown period.",
            "rights": "republicworld.com",
            "rank": 9700,
            "topic": "economics",
            "country": "US",
            "language": "en",
            "authors": [
                "Republic World"
            ],
            "media": "https://img.republicworld.com/republic-prod/stories/promolarge/xhdpi/zuxigutkx5ga6cqr_1648398016.jpeg",
            "is_opinion": false,
            "twitter_account": "@republic",
            "_score": 11.163196,
            "_id": "b06033cb87e9caf998961457afe87334"
        },
        {
            "title": "INTERACT: The most progressive, diverse conference for engineering leaders, Business News",
            "author": null,
            "published_date": "2022-03-29 09:00:00",
            "published_date_precision": "full",
            "link": "https://www.asiaone.com/business/interact-most-progressive-diverse-conference-engineering-leaders",
            "clean_url": "asiaone.com",
            "excerpt": "The popular community-driven engineering leadership conference returns on April 7th SEATTLE, March 29, 2022 /PRNewswire/ -- INTERACT, the community-driven conference for engineering leaders, is back…",
            "summary": "The popular community-driven engineering leadership conference returns on April 7th SEATTLE, March 29, 2022 /PRNewswire/ -- INTERACT, the community-driven conference for engineering leaders, is back for its second year. Featuring more than 50% female and minority speakers, INTERACT, hosted by LinearB, highlights some of the biggest names in engineering leadership, with speakers from Netflix, Slack, Stack Overflow, American Express, and more on April 7, 2022. INTERACT's free half-day virtual conference will host more than 1,500 engineering leaders from 75 different countries, features prominent influencers in software engineering, and has committed to accessibility measures including live captioning.",
            "rights": "asiaone.com",
            "rank": 4028,
            "topic": "business",
            "country": "SG",
            "language": "en",
            "authors": [],
            "media": "https://media.asiaone.com/sites/default/files/styles/a1_600x316/public/original_images/Mar2022/pr-newswire_500_4_1959.jpg?h=7de12b8a&itok=Tdi1c0MH",
            "is_opinion": false,
            "twitter_account": "@asiaonecom",
            "_score": 11.162927,
            "_id": "3a69e44b2aafda7c96880bbb85286325"
        },
        {
            "title": "Patti Engineering Hires Jeff Johnston as New Business Development Manager to Support Recent Surge in Industry Demand",
            "author": null,
            "published_date": "2022-03-29 00:00:00",
            "published_date_precision": "date",
            "link": "https://www.prweb.com/releases/patti_engineering_hires_jeff_johnston_as_new_business_development_manager_to_support_recent_surge_in_industry_demand/prweb18584867.htm",
            "clean_url": "prweb.com",
            "excerpt": "AUBURN HILLS, Mich. (PRWEB) March 29, 2022 -- Jeff Johnston brings nearly two decades of sales experience to the Patti Engineering team to support an increase in demand for the company's industrial…",
            "summary": "Jeff Johnston - New Business Development Manager 'Jeff brings a lot of integrity to our team,' said Sam Hoff, CEO of Patti Engineering. 'His many years of experience will complement our team's expertise and allow us to better serve our growing base of customers.' AUBURN HILLS, Mich. (PRWEB) March 29, 2022 Patti Engineering, a leading control system integration company based in Auburn Hills, MI with offices in Texas and Indiana, today announced the hire of Jeff Johnston as New Business Development Manager.",
            "rights": "prweb.com",
            "rank": 674,
            "topic": "tech",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "http://ww1.prweb.com/prfiles/2022/03/28/18584867/gI_120804_NewsImage_vcsPRAsset_530832_120804_4ac3818b-4b2e-41be-88c6-d4f719b828f0_0.png",
            "is_opinion": false,
            "twitter_account": "@PRWeb",
            "_score": 11.155138,
            "_id": "4d6f9f01712891e28dc0665232608f14"
        },
        {
            "title": "GLA University: Transforming engineering study to cope with the advancements",
            "author": null,
            "published_date": "2022-03-28 07:58:32",
            "published_date_precision": "full",
            "link": "https://www.hindustantimes.com/brand-stories/gla-university-transforming-engineering-study-to-cope-with-the-advancements-101648453938783.html",
            "clean_url": "hindustantimes.com",
            "excerpt": "Under the flagship of the Institute of Engineering & Technology, GLA University offers B.Tech programs in different specializations. Read on to know more!",
            "summary": "'Change is the law of life and those who look only to the past or present are certain to miss the future.' – John F. KennedyWith a firm belief in the above quote, GLA University always focuses on upgrading the course curriculum of engineering programs in sync with the trending technologies. The rewarding engineering career options of today will not be existing after a decade. In such a scenario, GLA University prepares its students for the ‘careers of the future'.Under the flagship of the Institute of Engineering &amp; Technology, GLA University offers B.",
            "rights": "hindustantimes.com",
            "rank": 1187,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": [],
            "media": "https://images.hindustantimes.com/img/2022/03/28/1600x900/B_(17)_1648454178496_1648454191223.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 11.144002,
            "_id": "b941d3c3e90c3691fd647290dbb7e7a0"
        },
        {
            "title": "LinearB: INTERACT: The most progressive, diverse conference for engineering leaders",
            "author": "Pr Newswire",
            "published_date": "2022-03-29 09:30:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.finanznachrichten.de/nachrichten-2022-03/55627474-linearb-interact-the-most-progressive-diverse-conference-for-engineering-leaders-008.htm",
            "clean_url": "finanznachrichten.de",
            "excerpt": "The popular community-driven engineering leadership conference returns on April 7th SEATTLE, March 29, 2022 /PRNewswire/ -- INTERACT, the community-driven conference for engineering",
            "summary": "The popular community-driven engineering leadership conference returns on April 7thSEATTLE, March 29, 2022 /PRNewswire/ -- INTERACT, the community-driven conference for engineering leaders, is back for its second year. Featuring more than 50% female and minority speakers, INTERACT, hosted by LinearB, highlights some of the biggest names in engineering leadership, with speakers from Netflix, Slack, Stack Overflow, American Express, and more on April 7, 2022.INTERACT's free half-day virtual conference will host more than 1,500 engineering leaders from 75 different countries, features prominent influencers in software engineering, and has committed to accessibility measures including live captioning.",
            "rights": "finanznachrichten.de",
            "rank": 7963,
            "topic": "news",
            "country": "DE",
            "language": "en",
            "authors": [
                "Pr Newswire"
            ],
            "media": "https://mma.prnewswire.com/media/1775086/Screen_Shot_2022_03_28_Logo.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 11.138737,
            "_id": "681629437cf0131915df02a5eaba83b6"
        },
        {
            "title": "Grainger holds Engineering Open House after two-year hiatus",
            "author": "Rohit Jammu",
            "published_date": "2022-03-24 16:00:06",
            "published_date_precision": "full",
            "link": "https://dailyillini.com/life_and_culture-stories/2022/03/24/engineering-open-house-2022",
            "clean_url": "dailyillini.com",
            "excerpt": "The Grainger College of Engineering ranks number ten in the top ten best schools for engineering, according to a 2021 report by US News. Within Grainger, computer engineering, aerospace engineering…",
            "summary": "The Grainger College of Engineering ranks number ten in the top ten best schools for engineering, according to a 2021 report by US News. Within Grainger, computer engineering, aerospace engineering and civil engineering also rank highly.\nWith so much high-ranking innovation at the University, the College of Engineering displays the talents of engineering students every year at the Engineering Open House.\nBeginning slightly over a century ago, the Engineering Open House is the University's demonstration of what it means to be a Grainger Engineer.",
            "rights": null,
            "rank": 44049,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Rohit Jammu"
            ],
            "media": "https://dailyillini.com/wp-content/uploads/2022/03/DSC_0134-900x600.jpg",
            "is_opinion": false,
            "twitter_account": "@TheDailyIllini",
            "_score": 11.092385,
            "_id": "21fae59b36622e5ee7f0d2e891423ca9"
        },
        {
            "title": "A Highly Efficient RF-DC Converter for Energy Harvesting Applications Using a Threshold Voltage Cancellation Scheme",
            "author": "Kang-Yoon Lee",
            "published_date": "2022-03-30 00:00:00",
            "published_date_precision": "date",
            "link": "https://www.mdpi.com/1424-8220/22/7/2659",
            "clean_url": "mdpi.com",
            "excerpt": "In this paper, a self-threshold voltage (Vth) compensated Radio Frequency to Direct Current (RF-DC) converter operating at 900 MHz and 2.4 GHz is proposed for RF energy harvesting applications. The…",
            "summary": "Muhammad Basim received his B.S. degree in Electrical Engineering (Telecommunication) from the University of Science and Technology Bannu, Pakistan, in 2015, and M.S. degree in Electrical and Computer Engineering from Sungkyunkwan University, Suwon, South Korea, in 2020. He served as a Researcher with the Integrated Circuits (IC) Laboratory, Sungkyunkwan University from March 2020 till August 2020. Currently, he is working towards his Ph.D. degree in Electronics and Electrical Engineering from Department of Electrical and Computer Engineering at Sungkyunkwan University, Suwon, Korea.",
            "rights": "Creative Commons Attribution (CC-BY)",
            "rank": 668,
            "topic": "science",
            "country": "CH",
            "language": "en",
            "authors": [
                "Muhammad Basim",
                "Danial Khan",
                "Qurat Ul Ain",
                "Khuram Shehzad",
                "Syed Adil Ali Shah",
                "Byeong-Gi Jang",
                "Young-Gun Pu",
                "Joon-Mo Yoo",
                "Joon-Tae Kim",
                "Kang-Yoon Lee"
            ],
            "media": "https://www.mdpi.com/sensors/sensors-22-02659/article_deploy/html/images/sensors-22-02659-g001-550.jpg",
            "is_opinion": false,
            "twitter_account": "@MDPIOpenAccess",
            "_score": 11.090954,
            "_id": "a1aaf509644d2e7fb0a543f9c3229e42"
        },
        {
            "title": "Explained: AICTE's revised rules for engineering education",
            "author": "Sourav Roy Barman",
            "published_date": "2022-03-30 10:24:07",
            "published_date_precision": "full",
            "link": "https://indianexpress.com/article/explained/aicte-revised-rules-for-engineering-education-7844398/",
            "clean_url": "indianexpress.com",
            "excerpt": "The AICTE has partially rolled back its radical move, made last year, to dispense with Physics and Mathematics as a mandatory high school subject combination for undergraduate four-year engineering…",
            "summary": "The All India Council for Technical Education (AICTE), which regulates technical education in the country, Tuesday issued revised norms on engineering education for the next academic year.\nThe AICTE ‘Approval Process Handbook 2022-23', which spells out the norms, covers a wide range of areas from entry-level qualifications for engineering aspirants to the setting up of new colleges in the technical education sector among others.\n🗞️ Subscribe Now: Get Express Premium to access the best Election reporting and analysis 🗞️https://images.",
            "rights": "indianexpress.com",
            "rank": 1201,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": [
                "Sourav Roy Barman"
            ],
            "media": "https://images.indianexpress.com/2022/03/students-6.jpg",
            "is_opinion": false,
            "twitter_account": "@indianexpress",
            "_score": 11.090467,
            "_id": "0505180ac4e56ab41716610eea714687"
        },
        {
            "title": "‘US News & World Report' releases latest graduate, professional program rankings",
            "author": "Sitenow Custom",
            "published_date": "2022-03-29 11:49:02",
            "published_date_precision": "full",
            "link": "https://now.uiowa.edu/2022/03/us-news-world-report-releases-latest-graduate-professional-program-rankings",
            "clean_url": "uiowa.edu",
            "excerpt": "The University of Iowa continues to climb in the U.S. News & World Report Best Graduate School rankings. According to the 2023 report, 66 UI colleges and programs were recognized among the best in…",
            "summary": "The University of Iowa continues to climb in the U.S. News & World Report Best Graduate School rankings. According to the 2023 report, 66 UI colleges and programs were recognized among the best in their field. Four of these programs, all in the College of Nursing, received a top-10 ranking. Each year, U.S. News ranks professional school programs in a variety of disciplines, including business, education, engineering, law, medicine, and nursing. Changes in this year's report include academic reputation rankings for graduate programs in social work; doctoral program rankings in the social sciences and humanities fields of economics and psychology; and doctoral program rankings in the science fields of math, statistics, biostatistics, biological sciences, computer science, chemistry, and earth sciences.",
            "rights": "uiowa.edu",
            "rank": 1039,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Sitenow Custom",
                "Https",
                "Sitenow.Uiowa.Edu"
            ],
            "media": "https://now.uiowa.edu/sites/now.uiowa.edu/files/wysiwyg_uploads/2019_06_24-Old%20Capitol-tschoon-006.jpg",
            "is_opinion": false,
            "twitter_account": "uiowa",
            "_score": 11.084587,
            "_id": "301cacf5e860072f71451774ad089f8a"
        },
        {
            "title": "Everest Group Announces Winners of Inaugural 2022 Engineering Services...",
            "author": null,
            "published_date": "2022-03-30 00:00:00",
            "published_date_precision": "date",
            "link": "https://www.prweb.com/releases/everest_group_announces_winners_of_inaugural_2022_engineering_services_peak_matrix_provider_of_the_year_awards/prweb18573007.htm",
            "clean_url": "prweb.com",
            "excerpt": "Capgemini, HCL Technologies and TCS tie for the No. 1 spot on the list of Top 15 Engineering Services Providers.(PRWeb March 30, 2022)Read the full story at https://www.prweb.com/releases/everest_group_announces_winners_of_inaugural_2022_engineering_services_peak_matrix_provider_of_the_year_awards/prweb18573007.htm",
            "summary": "Everest Group The Engineering Services PEAK Matrix Provider of the Year Awards identify the best of the best – Engineering Services providers with strong capabilities and successful services strategies that align well with evolving enterprise engineering needs\n\nEverest Group—a research firm focused on strategic IT, engineering services, business services and sourcing—today announced the winners of the 2022 Engineering Services PEAK Matrix Provider of the Year™. The awards, presented for the first time this year, recognize Engineering Services providers who have demonstrated consistent leadership in the PEAK Matrix® reports issued by Everest Group in the previous year (October 2020 to September 2021).",
            "rights": "prweb.com",
            "rank": 674,
            "topic": "tech",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "http://ww1.prweb.com/prfiles/2022/03/29/18573007/NewsImage_vcsPRAsset_1614988_159532_788c924e-a61f-44f8-a54f-1a3228d4100b_0.png",
            "is_opinion": false,
            "twitter_account": "@PRWeb",
            "_score": 11.084422,
            "_id": "a0d66aeb93f4399a0256ce12a6805532"
        },
        {
            "title": "Vikas Rajkumar Shukla's mechanical engineering world has kindled the flame of modern engineering",
            "author": null,
            "published_date": "2022-03-30 07:35:43",
            "published_date_precision": "full",
            "link": "https://www.dnaindia.com/business/report-vikas-rajkumar-shukla-s-mechanical-engineering-world-has-kindled-the-flame-of-modern-engineering-2942904",
            "clean_url": "dnaindia.com",
            "excerpt": "Vikas Rajkumar Shukla's mechanical engineering world has kindled the flame of modern engineering - New India is experiencing a revolutionary wave of experiential learning that has rekindled the flame…",
            "summary": "The earliest evidence of Engineering in India can be dated back to pre-historic times. Since then, this Nobel field has continued to amaze the youth to opt for it as a career. New India is experiencing a revolutionary wave of experiential learning that has rekindled the flame of learning about engineered products. Mechanical Engineering World has emerged as the guiding light for thousands who aspire to learn about new-age technology to excel in their domain of engineering. A lot of experts from one of the most prestigious institutions are part of the team of the page.",
            "rights": "COPYRIGHT @ 2022 DILIGENT MEDIA CORPORATION LTD. ALL RIGHTS RESERVED",
            "rank": 3103,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": [],
            "media": "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2022/03/30/1248914-picture322222.png",
            "is_opinion": false,
            "twitter_account": "@dna",
            "_score": 11.07637,
            "_id": "237175fc00eb31d8c9e1ae19b3475720"
        },
        {
            "title": "NLC GET Recruitment 2022 for 300 Graduate Executive Trainee (GET) Posts through GATE",
            "author": null,
            "published_date": "2022-03-24 06:03:28",
            "published_date_precision": "full",
            "link": "https://www.jagranjosh.com/articles/nlc-get-recruitment-2022-notification-check-online-application-link-1648101435-1",
            "clean_url": "jagranjosh.com",
            "excerpt": "NLC Recruitment 2022: NLC India Limited (NLC) is hiring 300 Graduate Executive Trainee (GET) at its official website @nlcindia.com. Check how to apply",
            "summary": "NLC Recruitment 2022: NLC India Limited (NLC) is hiring 300 Graduate Executive Trainee (GET) at its official website @nlcindia.com. Check how to apply NLC GET Recruitment 2022 steps, application link, Vacancy Details and Eligibility Criteria details below here. \n\n\n\n\n\n\n\nNLC GET Recruitment 2022\n\n NLC GET Recruitment 2022: NLC India Limited (NLC) will publish a recruitment notification for the post of Graduate Executive Trainee (GET) at its official website - nlcindia.com. A total of 300 vacancies are available of which 127 are for Thermal Power Stations & Renewable Energy and 173 for Mines and Allied Services.",
            "rights": "jagranjosh.com",
            "rank": 24994,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": [],
            "media": "https://img.jagranjosh.com/images/2022/March/2432022/nlc_img.JPG",
            "is_opinion": false,
            "twitter_account": "@Jagranjosh",
            "_score": 11.059846,
            "_id": "3dc53a7b81426b749172efb1c58e173a"
        },
        {
            "title": "Why study software engineering at Sydney",
            "author": null,
            "published_date": "2022-03-24 05:34:09",
            "published_date_precision": "full",
            "link": "https://www.sydney.edu.au/engineering/news-and-events/2022/03/24/why-study-software-engineering-at-sydney.html",
            "clean_url": "sydney.edu.au",
            "excerpt": "Studying biomedical engineering at Sydney allows you to learn from world class experts from a range of fields and apply your skills and knowledge to help people live longer, healthier lives.",
            "summary": "Because studying software engineering has its roots in engineering, computer science, and data science, you'll gain a range of valuable skills that make you an asset to hiring organisations.\nOur Bachelor of Engineering Honours (Software) draws on the underlying concepts of engineering such as analysis and design, development processes, and integration with wider systems, giving you the big picture understanding of developing effective software.\nWith this knowledge base, you'll have the opportunity to take on roles such as information security specialist, database programmer, system test engineer, web developer, or software analyst.",
            "rights": "sydney.edu.au",
            "rank": 2016,
            "topic": "news",
            "country": "AU",
            "language": "en",
            "authors": [],
            "media": "https://www.sydney.edu.au/content/dam/corporate/images/faculty-of-engineering-and-information-technologies/research/data-science-and-computer-engineering/computer-software-engineering.jpeg",
            "is_opinion": false,
            "twitter_account": "@Sydney_Uni",
            "_score": 11.028029,
            "_id": "b60516ac82a3114ea29c2fb6d7578e22"
        },
        {
            "title": "LEVEL Engineering opens a new office in Salt Lake City, Utah",
            "author": "Level Engineering",
            "published_date": "2022-03-28 18:45:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.wfmz.com/news/pr_newswire/pr_newswire_technology/level-engineering-opens-a-new-office-in-salt-lake-city-utah/article_11874ec7-cf2b-52ba-99b2-8815cf6cc111.html",
            "clean_url": "wfmz.com",
            "excerpt": "New LEVEL Engineering office open in Salt Lake City, Utah. LEVEL Engineering is a leading provider of Civil / Structural Engineering, Architecture, and Design. The Salt Lake City office provides",
            "summary": "New LEVEL Engineering office open in Salt Lake City, Utah. LEVEL Engineering is a leading provider of Civil / Structural Engineering, Architecture, and Design. The Salt Lake City office provides engineering and architectural services to Salt Lake City and surrounding areas – from Brigham City, Vernon, Provo, Sundance, Heber City, Ogden, Uintah, and American Fork.SALT LAKE CITY, March 28, 2022 /PRNewswire-PRWeb/ -- LEVEL Engineering, a leading provider of Civil / Structural Engineering, Architecture, and Design, is proud to announce the official opening of its Salt Lake City, Utah office.",
            "rights": "wfmz.com",
            "rank": 7903,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Level Engineering"
            ],
            "media": "https://bloximages.newyork1.vip.townnews.com/wfmz.com/content/tncms/custom/image/b9818ac0-ee9a-11e9-8e9f-a3b831b71481.jpg?resize=600%2C338",
            "is_opinion": false,
            "twitter_account": "@69News",
            "_score": 11.014059,
            "_id": "1f40b0537ad7c3d80b0beaa9df3fc4d8"
        },
        {
            "title": "Worldwide Engineering Research & Development Outsourcing Industry to 2025",
            "author": "Research",
            "published_date": "2022-03-24 19:00:00",
            "published_date_precision": "full",
            "link": "https://www.prnewswire.com/news-releases/worldwide-engineering-research--development-outsourcing-industry-to-2025---cross-divisional-innovations-in-major-industries-is-driving-growth-301509971.html",
            "clean_url": "prnewswire.com",
            "excerpt": "/PRNewswire/ -- The \"Global Engineering Research & Development (ER&D) Outsourcing Market: Analysis By Type (Embedded IT, Mechanic and Software) Size & Trends...",
            "summary": "DUBLIN, March 24, 2022 /PRNewswire/ -- The \"Global Engineering Research & Development (ER&D) Outsourcing Market: Analysis By Type (Embedded IT, Mechanic and Software) Size & Trends with Impact of Covid-19 and Forecast up to 2025\" report has been added to ResearchAndMarkets.com's offering. \nThe report provides an analysis of the global ER&D outsourcing market with market sizing and growth. The analysis includes market size in terms of value, market share by segments, and growth outlook of end-users of the market.",
            "rights": "prnewswire.com",
            "rank": 216,
            "topic": "world",
            "country": "US",
            "language": "en",
            "authors": [
                "Research"
            ],
            "media": "https://mma.prnewswire.com/media/539438/Research_and_Markets_Logo.jpg?p=facebook",
            "is_opinion": false,
            "twitter_account": "@PRNewswire",
            "_score": 10.984605,
            "_id": "e2f89fb88a692a805d6be363dc8ef162"
        },
        {
            "title": "‘U.S. News & World Report' Ranks Georgia Tech Graduate Programs Among the Best in the Nation",
            "author": null,
            "published_date": "2022-03-29 15:28:13",
            "published_date_precision": "full",
            "link": "http://news.gatech.edu/news/2022/03/29/us-news-world-report-ranks-georgia-tech-graduate-programs-among-best-nation",
            "clean_url": "gatech.edu",
            "excerpt": "The Georgia Institute of Technology's graduate programs were once again among the highest ranked in the nation in U.S. News & World Report's 2023 Best Graduate School Rankings. On the latest list,…",
            "summary": "The Georgia Institute of Technology's graduate programs were once again among the highest ranked in the nation in U.S. News & World Report's 2023 Best Graduate School Rankings. On the latest list, released March 29, Georgia Tech continues to be ranked in the top 10 for the College of Engineering and each of its specialties. Overall, the College of Engineering appears on the list at No. 7 among public universities, and each of its 11 programs was ranked ninth or better: Industrial and Systems Engineering – No.",
            "rights": "gatech.edu",
            "rank": 959,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "http://news.gatech.edu",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 10.983316,
            "_id": "dc497ba04a1fa01a2dcae0d4cc6cd8ed"
        },
        {
            "title": "JEE Main 2022: BTech Mechanical Engineering Cut-Offs For IITs Last Year",
            "author": null,
            "published_date": "2022-03-24 09:57:22",
            "published_date_precision": "full",
            "link": "https://www.ndtv.com/education/jee-main-2022-btech-mechanical-engineering-cut-offs-for-iits-from-last-year",
            "clean_url": "ndtv.com",
            "excerpt": "JEE Main 2022: BTech Mechanical Engineering Cut-Offs For IITs - Last year, six rounds of counselling were held and given below are the ranks at which the IITs closed admission to ME.",
            "summary": "New Delhi: The Indian Institutes of Technology (IITs) use the JEE Advanced scores for admissions to various programmes offered at the undergraduate (UG) engineering level at the IITs. All the IITs conduct separate counselling process through Joint Seat Allocation Authority (JoSAA). Last year, six rounds of counselling were held and given below are the ranks at which the IITs closed admission to Mechanical Engineering. The ranks given are for open, gender-neutral seats only. The cut-off ranks for reserved seats and seats for women and differently-abled candidates are different.",
            "rights": "ndtv.com",
            "rank": 895,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": [],
            "media": "https://cache.careers360.mobi/media/article_images/2022/3/24/jee-featured-image.jpg",
            "is_opinion": false,
            "twitter_account": "@careers360",
            "_score": 10.983016,
            "_id": "7e207bf525b3b0750303cef8ba6890e9"
        },
        {
            "title": "30 Forensic Engineering Expands Geotechnical Engineering Group in Vancouver with the appointment of Dr. Antone Debeet Ph.D., P.Eng. as Senior Associate",
            "author": "-30- Forensic Engineering",
            "published_date": "2022-03-30 14:03:53",
            "published_date_precision": "full",
            "link": "https://www.canadianunderwriter.ca/inspress/30-forensic-engineering-expands-geotechnical-engineering-group-in-vancouver-with-the-appointment-of-dr-antone-debeet-ph-d-p-eng-as-senior-associate",
            "clean_url": "canadianunderwriter.ca",
            "excerpt": "VANCOUVER, BC, MARCH, 30, 2022 /insPRESS/ – 30 Forensic Engineering, Canada's leading multidisciplinary forensic firm, is pleased to announce the appointment of Antone Dabeet Ph.D., P.Eng. as Senior Associate, within the Geotechnical Engineering group. Antone joins the 30 Forensic Engineering Vancouver office and…\nThe post 30 Forensic Engineering Expands Geotechnical Engineering Group in Vancouver with the appointment of Dr. Antone Debeet Ph.D., P.Eng. as Senior Associate appeared first on Canadian Underwriter.",
            "summary": "VANCOUVER, BC, MARCH, 30, 2022 /insPRESS/ – 30 Forensic Engineering, Canada's leading multidisciplinary forensic firm, is pleased to announce the appointment of Antone Dabeet Ph.D., P.Eng. as Senior Associate, within the Geotechnical Engineering group. Antone joins the 30 Forensic Engineering Vancouver office and will be a valuable, local technical resource to our Western Canada clients.\n\nDr. Dabeet possesses 15 years of experience in geotechnical engineering (9 years in consulting and 6 years in research) with emphasis on geotechnical seismic analysis and design.",
            "rights": "canadianunderwriter.ca",
            "rank": 57326,
            "topic": "news",
            "country": "CA",
            "language": "en",
            "authors": [
                "-30- Forensic Engineering"
            ],
            "media": "https://media.canadianunderwriter.ca/uploads/2022/03/30FE-logo-483-291-235deep-logo3.png",
            "is_opinion": false,
            "twitter_account": "@CdnUnderwriter",
            "_score": 10.975903,
            "_id": "1090af067f1b85f01f30fd93163bc245"
        },
        {
            "title": "Japan Airlines engineering division selects IFS solution for aircraft fleet maintenance",
            "author": null,
            "published_date": "2022-03-29 02:56:34",
            "published_date_precision": "full",
            "link": "https://finance.yahoo.com/news/japan-airlines-engineering-division-selects-025300796.html",
            "clean_url": "yahoo.com",
            "excerpt": "The chip giant isn't messing around as it looks to reclaim the top position in the semiconductor industry.",
            "summary": "JAL Engineering Co., Ltd. to deploy IFS aviation maintenance solution in the cloud to modernize long range maintenance planning for its nearly 200 aircraft fleet\n\nAnnouncement continues IFS expansion of its commercial aviation MRO footprint across Asia-Pacific and globally\n\nTOKYO, March 28, 2022 /PRNewswire/ -- IFS, the global cloud enterprise software company, today announced the Japan Airlines maintenance and engineering subsidiary, JAL Engineering Co., Ltd., has selected IFS to support fleet-wide long range maintenance planning.",
            "rights": "yahoo.com",
            "rank": 30,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://s.yimg.com/uu/api/res/1.2/YklPPODD8bphcfKdVV.UmA--~B/aD0xNjt3PTE2O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/prnewswire.com/a2e0d22beae4d1dabc30c6fcb3e568e4",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 10.94947,
            "_id": "64b5ab263d5e4101672de93c4523cb28"
        },
        {
            "title": "Boost your career with internationally accredited program",
            "author": "N T T T T T",
            "published_date": "2022-03-29 10:15:00",
            "published_date_precision": "full",
            "link": "https://manilastandard.net/tech/314217727/boost-your-career-with-internationally-accredited-program.html",
            "clean_url": "manilastandard.net",
            "excerpt": "Every year, thousands of fresh college graduates flood the local job market. With an oversupply of candidates for limited jobs, job",
            "summary": "Every year, thousands of fresh college graduates flood the local job market. With an oversupply of candidates for limited jobs, job hunting becomes a tight competition for aspiring professionals. Mechanical engineering On the other hand, for those who plan to establish themselves abroad, their job applications must be backed by credentials that prove their ability to become part of a global workforce.  As a jobseeker, how does one stand out and get selected? For aspiring engineers or information technology (IT) professionals, quality education ensures their qualification for related professions, and one clear indication of this is accreditations such as ABET.",
            "rights": "manilastandard.net",
            "rank": 40459,
            "topic": "news",
            "country": "JP",
            "language": "en",
            "authors": [
                "N T T T T T",
                "N T",
                "N T T",
                "N T T T",
                "N T T T T",
                "N T T T T T T T",
                "N T T T T T T T T T"
            ],
            "media": "https://manilastandard.net/wp-content/uploads/2022/03/abet.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 10.947333,
            "_id": "7789d569326ec69a3b9a51cb047a969c"
        },
        {
            "title": "Honor for Higginson",
            "author": "Article Maddy Lauria",
            "published_date": "2022-03-29 18:45:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.udel.edu/udaily/2022/march/american-society-mechanical-engineers-fellow-jill-higginson",
            "clean_url": "udel.edu",
            "excerpt": "American Society of Mechanical Engineers names UD's Jill Higginson 2022 Fellow",
            "summary": "Article by Maddy Lauria Photo illustration by Joy Smoker March 29, 2022 Jill Higginson, a professor of mechanical engineering and biomedical engineering at the University of Delaware, has been elected Fellow of the American Society of Mechanical Engineers (ASME).\nFewer than 3,500 of 64,428 current ASME members are Fellows, a prestigious distinction awarded to scholars with sustained significant engineering achievements who have been with the society for at least a decade.\n'Dr. Jill Higginson's election as a Fellow of the ASME is a well-deserved recognition of her contributions to the understanding of human muscle coordination using both experiments and simulations,' said Ajay Prasad, Engineering Alumni Distinguished Professor and chair of the Department of Mechanical Engineering.",
            "rights": "udel.edu",
            "rank": 804,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Article Maddy Lauria"
            ],
            "media": "https://www.udel.edu/content/dam/udelImages/udaily/2022/March/fb-jill-higginson-illustration-jsmoker-ASME800x420.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 10.944818,
            "_id": "a91fcd87f919ffa93e6b5c12c6653c08"
        },
        {
            "title": "Rashmiya Raviraj P.Eng. of 30 Forensic Engineering Joins 2022 National Engineering Month Discussion: ‘Engineering the Future'",
            "author": "-30- Forensic Engineering",
            "published_date": "2022-03-29 15:54:18",
            "published_date_precision": "full",
            "link": "https://www.canadianunderwriter.ca/inspress/rashmiya-raviraj-p-eng-of-30-forensic-engineering-joins-2022-national-engineering-month-discussion-engineering-the-future",
            "clean_url": "canadianunderwriter.ca",
            "excerpt": "TORONTO, ON, March, 29, 2022 /insPRESS/ – 30 Forensic Engineering, Canada's leading multidisciplinary forensic firm, is pleased to announce that Rashmiya Raviraj B.A.Sc., CFEI, P.Eng., Practice Lead, Fire & Electrical, has been invited to join the panel for the National Engineering Month…\nThe post Rashmiya Raviraj P.Eng. of 30 Forensic Engineering Joins 2022 National Engineering Month Discussion: ‘Engineering the Future' appeared first on Canadian Underwriter.",
            "summary": "TORONTO, ON, March, 29, 2022 /insPRESS/ – 30 Forensic Engineering, Canada's leading multidisciplinary forensic firm, is pleased to announce that Rashmiya Raviraj B.A.Sc., CFEI, P.Eng., Practice Lead, Fire & Electrical, has been invited to join the panel for the National Engineering Month discussion, ‘Engineering the Future‘. Presented in conjunction with the Ontario Society of Professional Engineers, and with the support of hEr VOLUTION, this highly anticipated dialogue will bring forward women in engineering to discuss opportunities in the field for young women and how we can foster collaboration and initiatives to achieve the goal of 30 by 30.",
            "rights": "canadianunderwriter.ca",
            "rank": 57326,
            "topic": "news",
            "country": "CA",
            "language": "en",
            "authors": [
                "-30- Forensic Engineering"
            ],
            "media": "https://media.canadianunderwriter.ca/uploads/2022/03/30FE-logo-483-291-235deep-logo2.png",
            "is_opinion": false,
            "twitter_account": "@CdnUnderwriter",
            "_score": 10.930092,
            "_id": "779ed16f28d4df51a3b4de1fff80ba5c"
        },
        {
            "title": "Industrial engineering degree jobs: All of your options",
            "author": "Melissa Sartore",
            "published_date": "2022-03-30 17:47:00",
            "published_date_precision": "full",
            "link": "https://www.zdnet.com/education/science-engineering/industrial-engineering-jobs/",
            "clean_url": "zdnet.com",
            "excerpt": "Industrial engineers optimize workplace systems and operations. Start optimizing your search for industrial engineering degree jobs here.",
            "summary": "Industrial engineering degree jobs apply engineering principles and practices to production processes.As an industrial engineer, you can focus on manufacturing processes or embrace the field's versatility by working in business, government, and healthcare settings. Industrial engineering overlaps with supply chain management. Professionals identify ways to reduce costs, minimize inventory, and efficiently move goods and services from place to place.Keep reading to learn more about life as an industrial engineer, your potential roles, and possible pay.",
            "rights": "zdnet.com",
            "rank": 298,
            "topic": "economics",
            "country": "US",
            "language": "en",
            "authors": [
                "Melissa Sartore"
            ],
            "media": "https://www.zdnet.com/a/img/resize/97f8b270af80136376754900aefefe27b6ce2948/2019/01/23/21040f13-3c6d-4370-a23d-65cfeda8532d/istock-1023232352.jpg?width=770&height=578&fit=crop&auto=webp",
            "is_opinion": false,
            "twitter_account": "@ZDNet",
            "_score": 10.927534,
            "_id": "bbd9057bafd2cc1c83f83e01143618b9"
        },
        {
            "title": "Funding reforms ‘another blow' to engineering education",
            "author": "Twitter",
            "published_date": "2022-03-28 09:35:00",
            "published_date_precision": "full",
            "link": "https://www.timeshighereducation.com/news/funding-reforms-another-blow-engineering-education",
            "clean_url": "timeshighereducation.com",
            "excerpt": "Canberra's policy changes helped turn its big-ticket infrastructure schemes into pipe dreams, university-industry report argues",
            "summary": "Last year's Job-ready Graduates (JRG) reforms exacerbated pre-existing problems with Australian engineering education so severely that the government's signature infrastructure projects may never see the light of day, a new report warns.\nThe Group of Eight (Go8) research-intensive universities says the government will need to spend A$1.25 billion (£715 million) a year to fix funding anomalies and double the supply of homegrown engineers.\nOtherwise, nation-building projects including a fleet of nuclear-powered submarines, a new hydrogen industry, a rebooted civil space industry and a strategy to scale up manufacturing will never come to fruition.",
            "rights": "timeshighereducation.com",
            "rank": 1838,
            "topic": "news",
            "country": "GB",
            "language": "en",
            "authors": [
                "Twitter"
            ],
            "media": "https://www.timeshighereducation.com/sites/default/files/female-engineer.jpg",
            "is_opinion": false,
            "twitter_account": "@timeshighered",
            "_score": 10.927213,
            "_id": "a4babf1298871f6c46f1b8f04e6171f9"
        },
        {
            "title": "Leveraging AI to Work with Cells",
            "author": "Northwestern University McCormick School of Engineering March 24, 2022\nComments",
            "published_date": "2022-03-24 17:45:00",
            "published_date_precision": "timezone unknown",
            "link": "https://cacm.acm.org/news/259549-leveraging-ai-to-work-with-cells/fulltext",
            "clean_url": "acm.org",
            "excerpt": "The research team's automated NFP-E enables selective cell engineering at higher throughputs than manual probe-based methods, while also reducing experimental variability and enabling more efficient…",
            "summary": "The research team's automated NFP-E enables selective cell engineering at higher throughputs than manual probe-based methods, while also reducing experimental variability and enabling more efficient engineering of human induced pluripotent stem cell\nCredit: Vincent Lemaitre, Infinitesimal LLC\n\n\n\nResearchers at Northwestern University developed a new version of their Nanofountain Probe Electroporation (NFP-E) tool to execute cell engineering tasks using artificial intelligence, which could help develop personalized diagnostics and treatments.",
            "rights": "acm.org",
            "rank": 718,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Northwestern University Mccormick School Of Engineering"
            ],
            "media": "https://cacm.acm.org/system/assets/0004/2615/032422_Vincent_Lemaitre_Infinitesimal_LLC_leveraging-ai-to-work-with-cells-research-image.large.jpg?1648138757&1648138757",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 10.920766,
            "_id": "3565d1c025ac3d231662a6066589d574"
        },
        {
            "title": "Norms revised: Physics, Maths a must to pursue engineering, tech UG courses",
            "author": "Sourav Roy Barman",
            "published_date": "2022-03-29 21:57:54",
            "published_date_precision": "full",
            "link": "https://indianexpress.com/article/education/norms-revised-physics-maths-a-must-to-pursue-engineering-tech-ug-courses-7843443/",
            "clean_url": "indianexpress.com",
            "excerpt": "The previous norms had left the question of mandatory subject combinations on the universities and engineering institutes, making it technically possible for those who may not have studied Physics and…",
            "summary": "ADMISSIONS TO most engineering and technology undergraduate degree programmes will require students to have mandatorily pursued Physics and Mathematics at the high school level, the All Indian Council for Technical Education (AICTE) announced on Tuesday, in what is being seen as a partial rollback of the eligibility norms it released last year.\nThe previous norms had left the question of mandatory subject combinations on the universities and engineering institutes, making it technically possible for those who may not have studied Physics and Maths at the higher secondary level to pursue UG degree courses in engineering and technology.",
            "rights": "indianexpress.com",
            "rank": 1201,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": [
                "Sourav Roy Barman"
            ],
            "media": "https://images.indianexpress.com/2022/03/engineering-1200.jpg",
            "is_opinion": false,
            "twitter_account": "@indianexpress",
            "_score": 10.917433,
            "_id": "b3082ce16b3e262d882ecee0e3b2940c"
        },
        {
            "title": "Faros Community Edition",
            "author": null,
            "published_date": "2022-03-29 21:59:42",
            "published_date_precision": "full",
            "link": "https://www.producthunt.com/posts/faros-community-edition",
            "clean_url": "producthunt.com",
            "excerpt": "Faros Community Edition (CE) is an open-source engineering operations platform that connects the dots between all your operational data sources for a single-pane view across the software development…",
            "summary": "Faros Community Edition (CE) is an open-source engineering operations platform that connects the dots between all your operational data sources for a single-pane view across the software development life cycle.Featured 3h agoHave you used Faros Community Edition?Help improve Product Hunt by sharing a review with the community.Stack Overflow on MobileQ&A for software engineering problemsOpenVSCode ServerVS Code in the browser for everyoneVectorly 2.0Develop high-performing engineering & design teamsSourcing.",
            "rights": "producthunt.com",
            "rank": 2351,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://ph-files.imgix.net/3c9d4c47-4a24-41c8-a903-a3b4d50b92cb.png?auto=format&fit=crop&frame=1&h=512&w=1024",
            "is_opinion": false,
            "twitter_account": "@producthunt",
            "_score": 10.913679,
            "_id": "48ce07d17f7e42bce1ef77aea667d84f"
        },
        {
            "title": "Automotive Engineering Services Market Size to Hit US$ 360.22 Bn by 2030",
            "author": "Precedence Research",
            "published_date": "2022-03-25 00:00:00",
            "published_date_precision": "date",
            "link": "https://www.globenewswire.com/news-release/2022/03/25/2410001/0/en/Automotive-Engineering-Services-Market-Size-to-Hit-US-360-22-Bn-by-2030.html",
            "clean_url": "globenewswire.com",
            "excerpt": "According to Precedence Research, the automotive engineering services market size is predicted to surpass US$ 360.22 billion by 2030 with a growing CAGR of...",
            "summary": "London, March 25, 2022 (GLOBE NEWSWIRE) -- The global automotive engineering services market size was estimated at US$ 170.25 billion in 2021. The automotive engineering services market is expected to be driven by the growing technological skills for engineering service providers to offer research and development and product innovation in their solutions for connected automobiles, vehicle positioning, and guidance systems. In addition, the automotive engineering services market's overall growth is likely to benefit from original equipment manufacturers rapid shift in preference for digital solutions over mechanical and core assistance.",
            "rights": "globenewswire.com",
            "rank": 610,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Precedence Research"
            ],
            "media": "https://ml.globenewswire.com/Resource/Download/501140d4-82c8-4a65-82a7-8466b5188635?size=1",
            "is_opinion": false,
            "twitter_account": "globenewswire",
            "_score": 10.912188,
            "_id": "216587cda18435da8ca4897803fe5f34"
        },
        {
            "title": "More on engineering and science",
            "author": "Paul Heney",
            "published_date": "2022-03-25 18:10:44",
            "published_date_precision": "full",
            "link": "https://www.designworldonline.com/more-on-engineering-and-science",
            "clean_url": "designworldonline.com",
            "excerpt": "In January, I talked about how engineers and scientists really are kindred spirits, as they play on the same team of knowledge seekers. And hopefully you",
            "summary": "In January, I talked about how engineers and scientists really are kindred spirits, as they play on the same team of knowledge seekers. And hopefully you read the fascinating 'Leadership in Engineering' feature article on Dan Arvizu, the Chancellor of New Mexico State University, who has been a leader and a trailblazer his whole career.\nPaul J. Heney and Dan Arvizu.\nIn the month since our discussion, I got to thinking about something Arvizu said to me about engineering and science, and how he saw the two disciplines constantly intertwine, based on his long career in research and development.",
            "rights": "designworldonline.com",
            "rank": 36006,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Paul Heney"
            ],
            "media": "https://www.designworldonline.com/wp-content/uploads/IMG_6283.jpg",
            "is_opinion": false,
            "twitter_account": "@DesignWorld",
            "_score": 10.909114,
            "_id": "a144e7d6a521731baf10837742e89c82"
        },
        {
            "title": "Rajesh P. N. Rao",
            "author": null,
            "published_date": "2022-03-30 15:30:00",
            "published_date_precision": "timezone unknown",
            "link": "https://theconversation.com/profiles/rajesh-p-n-rao-353521",
            "clean_url": "theconversation.com",
            "excerpt": "Rajesh P. N. Rao — Profile on The Conversation",
            "summary": "Professor of Computer Science and Engineering and Director of the Center for Sensorimotor Neural Engineering, University of Washington Rajesh P. N. Rao is the Director of the NSF Center for Sensorimotor Neural Engineering (CSNE) and Professor in the Computer Science and Engineering department, Adjunct Professor in the EE and BioE departments, and faculty member in the Neuroscience Graduate Program at the University of Washington (UW), Seattle. He received his PhD from the University of Rochester and was an Alfred P.",
            "rights": "theconversation.com",
            "rank": 361,
            "topic": "news",
            "country": "AU",
            "language": "en",
            "authors": [],
            "media": "https://cdn.theconversation.com/avatars/353521/width238/RRao.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 10.900318,
            "_id": "42b1964e6d2e362bdc621ca945655035"
        },
        {
            "title": "Japan Airlines engineering division selects IFS solution for aircraft fleet maintenance",
            "author": "IFS",
            "published_date": "2022-03-29 02:53:00",
            "published_date_precision": "full",
            "link": "https://www.prnewswire.com/news-releases/japan-airlines-engineering-division-selects-ifs-solution-for-aircraft-fleet-maintenance-301512354.html",
            "clean_url": "prnewswire.com",
            "excerpt": "/PRNewswire/ -- IFS, the global cloud enterprise software company, today announced the Japan Airlines maintenance and engineering subsidiary, JAL Engineering...",
            "summary": "JAL Engineering Co., Ltd. to deploy IFS aviation maintenance solution in the cloud to modernize long range maintenance planning for its nearly 200 aircraft fleet           \nAnnouncement continues IFS expansion of its commercial aviation MRO footprint across Asia-Pacific and globally\n\nTOKYO, March 28, 2022 /PRNewswire/ -- IFS, the global cloud enterprise software company, today announced the Japan Airlines maintenance and engineering subsidiary, JAL Engineering Co., Ltd., has selected IFS to support fleet-wide long range maintenance planning.",
            "rights": "prnewswire.com",
            "rank": 216,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "IFS"
            ],
            "media": "https://www.prnewswire.com:443/content/dam/prnewswire/icons/2019-Q4-PRN-Icon-32-32.png",
            "is_opinion": false,
            "twitter_account": "@PRNewswire",
            "_score": 10.894885,
            "_id": "09f946b544187d5c512b09378089e912"
        },
        {
            "title": "Japan Airlines engineering division selects IFS solution for aircraft fleet maintenance, Business News",
            "author": null,
            "published_date": "2022-03-29 03:15:00",
            "published_date_precision": "full",
            "link": "https://www.asiaone.com/business/japan-airlines-engineering-division-selects-ifs-solution-aircraft-fleet-maintenance",
            "clean_url": "asiaone.com",
            "excerpt": "JAL Engineering Co., Ltd. to deploy IFS aviation maintenance solution in the cloud to modernize long range maintenance planning for its nearly 200 aircraft fleet Announcement continues IFS expansion…",
            "summary": "JAL Engineering Co., Ltd. to deploy IFS aviation maintenance solution in the cloud to modernize long range maintenance planning for its nearly 200 aircraft fleet            Announcement continues IFS expansion of its commercial aviation MRO footprint across Asia-Pacific and globally TOKYO, March 29, 2022 /PRNewswire/ -- IFS, the global cloud enterprise software company, today announced the Japan Airlines maintenance and engineering subsidiary, JAL Engineering Co., Ltd., has selected IFS to support fleet-wide long range maintenance planning.",
            "rights": "asiaone.com",
            "rank": 4028,
            "topic": "business",
            "country": "SG",
            "language": "en",
            "authors": [],
            "media": "https://media.asiaone.com/sites/default/files/styles/a1_600x316/public/original_images/Mar2022/pr-newswire_500_4_1918.jpg?h=7de12b8a&itok=CCwY95mH",
            "is_opinion": false,
            "twitter_account": "@asiaonecom",
            "_score": 10.892639,
            "_id": "1554f9965461336f73476f3e20fd4f6b"
        },
        {
            "title": "UNBC celebrates engineering month with upcoming open house",
            "author": "Citizen staff",
            "published_date": "2022-03-28 22:48:00",
            "published_date_precision": "full",
            "link": "https://www.princegeorgecitizen.com/local-news/unbc-celebrates-engineering-month-with-upcoming-open-house-5207298",
            "clean_url": "princegeorgecitizen.com",
            "excerpt": "‘Engineering graduates are in high demand in British Columbia'",
            "summary": "The University of Northern British Columbia (UNBC)'s new school of engineering is celebrating engineering month by recognizing the importance of local industry, engaging with prospective students, and sharing the history of civil engineering in Canada. 'Engineering is a vital profession for communities in northern B.C. and across British Columbia that brings enormous economic benefits to industry towns like Prince George,' said Anne Kang, Minister of Advanced Education and Skills Training. 'Engineering Month is an opportunity to improve the understanding of what engineers do, the crucial role they play in our lives, and showcase the benefits a career in engineering offers.",
            "rights": "princegeorgecitizen.com",
            "rank": 54923,
            "topic": "news",
            "country": "CA",
            "language": "en",
            "authors": [
                "Citizen staff"
            ],
            "media": "https://www.vmcdn.ca/f/files/princegeorgematters/pgc-images/educations/unbc-engineering.jpg;w=800;h=534;mode=crop",
            "is_opinion": false,
            "twitter_account": "@pgcitizen",
            "_score": 10.877768,
            "_id": "159b128a2698602d521032e5151dd7c0"
        },
        {
            "title": "Japan Airlines engineering division selects IFS solution for aircraft fleet maintenance",
            "author": "IFS",
            "published_date": "2022-03-29 02:53:00",
            "published_date_precision": "full",
            "link": "https://www.wfmz.com/news/pr_newswire/pr_newswire_business/japan-airlines-engineering-division-selects-ifs-solution-for-aircraft-fleet-maintenance/article_9beb3cc3-fa2d-5cba-ae29-8e84deb3e502.html",
            "clean_url": "wfmz.com",
            "excerpt": "JAL Engineering Co., Ltd. to deploy IFS aviation maintenance solution in the cloud to modernize long range maintenance planning for its nearly 200 aircraft fleet Announcement continues IFS expansion…",
            "summary": "JAL Engineering Co., Ltd. to deploy IFS aviation maintenance solution in the cloud to modernize long range maintenance planning for its nearly 200 aircraft fleet           Announcement continues IFS expansion of its commercial aviation MRO footprint across Asia-Pacific and globallyTOKYO, March 28, 2022 /PRNewswire/ -- IFS, the global cloud enterprise software company, today announced the Japan Airlines maintenance and engineering subsidiary, JAL Engineering Co., Ltd., has selected IFS to support fleet-wide long range maintenance planning.",
            "rights": "wfmz.com",
            "rank": 7903,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "IFS"
            ],
            "media": "https://bloximages.newyork1.vip.townnews.com/wfmz.com/content/tncms/custom/image/b9818ac0-ee9a-11e9-8e9f-a3b831b71481.jpg?resize=600%2C338",
            "is_opinion": false,
            "twitter_account": "@69News",
            "_score": 10.876225,
            "_id": "09a3f545048f79e82cb0b8ac28e4ae49"
        },
        {
            "title": "Sierra engineers her future through Kiewit Scholars Program",
            "author": "https://www.facebook.com/NebraskaToday",
            "published_date": "2022-03-24 05:22:00",
            "published_date_precision": "full",
            "link": "https://news.unl.edu/newsrooms/today/article/sierra-engineers-her-future-through-kiewit-scholars-program",
            "clean_url": "unl.edu",
            "excerpt": "Sierra, a freshman mechanical engineering major from Chicago, is one of 10 students chosen for the program's inaugural cohort. She applied as the program would provide the tools and support needed to…",
            "summary": "Felicity Sierra is charting her own path in engineering through the University of Nebraska–Lincoln's Kiewit Scholars Program. Sierra, a freshman mechanical engineering major from Chicago, was one of 10 students chosen for the program's inaugural cohort last fall. The program is a collaboration between the College of Engineering and Kiewit Corporation that aims to provide a select cohort of engineering students with leadership and career development opportunities throughout their undergraduate experience.",
            "rights": "unl.edu",
            "rank": 1030,
            "topic": "science",
            "country": "US",
            "language": "en",
            "authors": [
                "https://www.facebook.com/NebraskaToday"
            ],
            "media": "https://news.unl.edu/sites/default/files/styles/large_sixteen_by_nine/public/media/202203XX-felicitysierra-nt.jpg?itok=rVoQpyNc",
            "is_opinion": false,
            "twitter_account": "@UNLincoln",
            "_score": 10.873056,
            "_id": "6db8a0c857a81f405b71e2679cf768bf"
        }
    ],
    "user_input": {
        "q": "Engineering || \"Computer Science || India\"",
        "search_in": [
            "title_summary"
        ],
        "lang": [
            "en"
        ],
        "not_lang": null,
        "countries": null,
        "not_countries": null,
        "from": "2022-03-24 00:00:00",
        "to": null,
        "ranked_only": "True",
        "from_rank": null,
        "to_rank": null,
        "sort_by": "relevancy",
        "page": 1,
        "size": 50,
        "sources": null,
        "not_sources": null,
        "topic": null,
        "published_date_precision": null
    }
}]