export const news = [{
    "status": "ok",
    "total_hits": 10000,
    "page": 1,
    "total_pages": 200,
    "page_size": 50,
    "articles": [
        {
            "title": "Bitcoin Evolution Review 2022- Scam or Legit?",
            "author": "Michael Graw Last updated: 14 March 2022",
            "published_date": "2022-03-14 16:29:31",
            "published_date_precision": "full",
            "link": "https://www.business2community.com/cryptocurrency/bitcoin-robots/bitcoin-evolution-review",
            "clean_url": "business2community.com",
            "excerpt": "Business 2 Community - Top Trends, News & Expert Analysis",
            "summary": "Bitcoin Evolution is a crypto trading robot that can trade Bitcoin and other popular cryptocurrencies automatically. According to Bitcoin Evolution, you don't need any experience to start using this software and there are no trading fees to worry about. The platform can trade 24/7, ensuring you never miss a chance to trade in the ever-moving crypto market.\nSo, is Bitcoin Evolution legit? Our Bitcoin Evolution review will cover everything you need to know about this crypto robot.\nBitcoin Evolution Summary\nLet's start off our Bitcoin Evolution review with a quick summary of this crypto trading platform:\n\n\n\n\nTradable Assets\nBTC, ETH, LTC, DASH, Forex\n\n\nTrading Hours\n24/7\n\n\nClaimed Success Rate\nNone\n\n\nExperience Required?\nNo\n\n\nMinimum Deposit\n$250\n\n\nMobile App\nNo\n\n\n\n\nWhat is Bitcoin Evolution?\nBitcoin Evolution is an automated crypto trading platform, also known as a Bitcoin robot.",
            "rights": "business2community.com",
            "rank": 1748,
            "topic": "business",
            "country": "US",
            "language": "en",
            "authors": [
                "Author"
            ],
            "media": "https://cdn.business2community.com/B2C_FB.png",
            "is_opinion": false,
            "twitter_account": "@b2community",
            "_score": 9.436228,
            "_id": "78b52000133423ed84b9475c6607fc96"
        },
        {
            "title": "Bitcoin Trading Market Share 2022 Global Statistics, Industry Trends, Competition Strategies, Revenue Analysis, Key Players, Regional Analysis by Forecast to 2027",
            "author": "TheExpressWire",
            "published_date": "2022-03-14 11:01:37",
            "published_date_precision": "full",
            "link": "https://www.digitaljournal.com/pr/bitcoin-trading-market-share-2022-global-statistics-industry-trends-competition-strategies-revenue-analysis-key-players-regional-analysis-by-forecast-to-2027",
            "clean_url": "digitaljournal.com",
            "excerpt": "The Bitcoin Trading Market report additionally, this report covers the manufacturers' data, including business distribution, cost and price, margin, and gross revenue. Bitcoin Trading Market report…",
            "summary": "The Bitcoin Trading Market report additionally, this report covers the manufacturers' data, including business distribution, cost and price, margin, and gross revenue. Bitcoin Trading Market report allows a reader to understand consumers' behavior and a better understanding of the leading competitor's operation in the market.\n\nGlobal Bitcoin Trading Market includes Precise company profiling of leading players of the Bitcoin Trading market. All of the segments studied in the report are analyzed based on different factors such as market share, revenue, and CAGR.",
            "rights": "digitaljournal.com",
            "rank": 1610,
            "topic": "economics",
            "country": "CA",
            "language": "en",
            "authors": [
                "Karen Graham",
                "Written By"
            ],
            "media": "https://secure.gravatar.com/avatar/a5936643cfb93345023945704b62c134?s=150&d=blank&r=pg",
            "is_opinion": false,
            "twitter_account": "@digitaljournal",
            "_score": 9.391673,
            "_id": "5db69d48dac748ebf504b4e1d7e68e18"
        },
        {
            "title": "EU Parliament votes against ban on proof-of-work mechanism underlying cryptos like Bitcoin : Bitcoin",
            "author": "/u/oOSchwippiOo",
            "published_date": "2022-03-14 15:46:29",
            "published_date_precision": "full",
            "link": "https://www.reddit.com/r/Bitcoin/comments/te0gx7/eu_parliament_votes_against_ban_on_proofofwork",
            "clean_url": "reddit.com",
            "excerpt": "https://finbold.com/breaking-eu-parliament-votes-against-ban-on-proof-of-work-mechanism-underlying-cryptos-like-bitcoin/ submitted by /u/oOSchwippiOo [link] [comments]",
            "summary": "Bitcoin is the currency of the Internet: a distributed, worldwide, decentralized digital money. Unlike traditional currencies such as dollars, bitcoins are issued and managed without any central authority whatsoever: there is no government, company, or bank in charge of Bitcoin. As such, it is more resistant to wild inflation and corrupt banks. With Bitcoin, you can be your own bank.",
            "rights": "reddit.com",
            "rank": 38,
            "topic": "finance",
            "country": "US",
            "language": "en",
            "authors": [
                "/u/oOSchwippiOo"
            ],
            "media": "https://external-preview.redd.it/5TP4zKfFPUDAcdL32eMfHy0kmbp7X6Vi9EOsxeqLZLQ.jpg?auto=webp&s=6e83c967e9b287a4250f245f4a952c3856d3c37e",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.2706,
            "_id": "9c164da68fdff5f9100ec1ad0bedfc0d"
        },
        {
            "title": "Things one should keep in mind before investing in Bitcoins",
            "author": null,
            "published_date": "2022-03-08 14:41:04",
            "published_date_precision": "full",
            "link": "http://www.tmcnet.com/topics/articles/2022/03/08/451741-things-one-should-keep-mind-before-investing-bitcoins.htm",
            "clean_url": "tmcnet.com",
            "excerpt": "I am not a Bitcoin expert, but Bitcoin is an interesting topic. Bitcoin has been marketed as a currency but also as a trading instrument. I decided to write this article because Bitcoin seems to attract a lot of people who don't understand the risks involved - or worse - they understand them and still invest. For those people I wrote some things that one should keep in mind before investing in Bitcoins. You can also visit the Bitcoin Era for keeping yourself up to date with the latest knowledge about bitcoin investment.",
            "summary": "March 08, 2022\n\nI am not a Bitcoin expert, but Bitcoin is an interesting topic. Bitcoin has been marketed as a currency but also as a trading instrument. I decided to write this article because Bitcoin seems to attract a lot of people who don't understand the risks involved – or worse – they understand them and still invest. For those people I wrote some things that one should keep in mind before investing in Bitcoins. You can also visit the Bitcoin Era for keeping yourself up to date with the latest knowledge about bitcoin investment.",
            "rights": "tmcnet.com",
            "rank": 3926,
            "topic": "tech",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://images.tmcnet.com/tmc/misc/articles/image/2022-mar/1707056113-bitcoin4.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.265785,
            "_id": "041e9017fce9cc5d2c617a23f08630c4"
        },
        {
            "title": "Riot Stock Looks Attractive After A Deep Correction (NASDAQ:RIOT)",
            "author": null,
            "published_date": "2022-03-14 21:32:17",
            "published_date_precision": "full",
            "link": "https://seekingalpha.com/article/4495423-riot-stock-attractive-after-deep-correction",
            "clean_url": "seekingalpha.com",
            "excerpt": "Riot expects multi-fold growth in mining capacity, which will translate into robust revenue growth. Here's why I'm bullish on RIOT stock.",
            "summary": "Tevarak/iStock via Getty Images Investment Overview Bitcoin mining companies had a strong rally in the first quarter of 2021. This was a period when Bitcoin surged. With volatility and correction in the cryptocurrency world, Bitcoin miners have struggled. With Bitcoin slipping below $40,000, some miners look attractive from a medium to long-term investment perspective. Riot Blockchain (RIOT) is one name that deserves a place in the portfolio. This initiating coverage on Riot stock will discuss the factors that make the Bitcoin mining company attractive at current levels of $15.",
            "rights": "seekingalpha.com",
            "rank": 951,
            "topic": "finance",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://static.seekingalpha.com/cdn/s3/uploads/getty_images/1320532557/image_1320532557.jpg?io=getty-c-w750",
            "is_opinion": false,
            "twitter_account": "@SeekingAlpha",
            "_score": 9.265522,
            "_id": "ee6a41a2bd95614fefe8cbc4a6b9af16"
        },
        {
            "title": "Bitcoin 2022 Is At The Center Of Something Much Bigger Happening Globally",
            "author": null,
            "published_date": "2022-03-14 13:53:31",
            "published_date_precision": "full",
            "link": "https://finance.yahoo.com/news/bitcoin-2022-center-something-much-135331920.html",
            "clean_url": "yahoo.com",
            "excerpt": "Bitcoin was trading flat to negative even as the European stocks and the S&P 500 futures got a slight tailwind.",
            "summary": "Bitcoin 2021 changed the game. Bitcoin 2022 will change the world.\n\nMiami, FL --News Direct-- 21MillonesBTC.com\n\nEducation, Celebration, Hyperbitcoinization\n\nBitcoin Week exists beyond the Bitcoin Conference as a powerful part of the broader movement towards hyperbitcoinization.\n\n21MillonesBTC.com is excited to see Miami Beach as the center of Bitcoin Week 2022 and is happy to not only participate but also contribute so that the Hispanic community in South Florida and Latin America can be represented.",
            "rights": "yahoo.com",
            "rank": 30,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://s.yimg.com/ny/api/res/1.2/c46ajBD4ZXNbEpXo.Oo1eg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD01ODM-/https://s.yimg.com/uu/api/res/1.2/i7cD31YmehevKkkjhSO7CA--~B/aD03NDY7dz0xNTM2O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/news_direct/0ef6cee310e320b67b07a158d245ddac",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.256381,
            "_id": "261134e1c3c75ee3d8e49ea2b324f108"
        },
        {
            "title": "New Gallup Poll Gives El Salvador's President Bukele An 85% Approval Rating — Thanks To His Bitcoin Experiment : Bitcoin",
            "author": "/u/poomata",
            "published_date": "2022-03-14 14:03:12",
            "published_date_precision": "full",
            "link": "https://www.reddit.com/r/Bitcoin/comments/tdy7xt/new_gallup_poll_gives_el_salvadors_president",
            "clean_url": "reddit.com",
            "excerpt": "submitted by /u/poomata [link] [comments]",
            "summary": "Bitcoin is the currency of the Internet: a distributed, worldwide, decentralized digital money. Unlike traditional currencies such as dollars, bitcoins are issued and managed without any central authority whatsoever: there is no government, company, or bank in charge of Bitcoin. As such, it is more resistant to wild inflation and corrupt banks. With Bitcoin, you can be your own bank.",
            "rights": "reddit.com",
            "rank": 38,
            "topic": "finance",
            "country": "US",
            "language": "en",
            "authors": [
                "/u/poomata"
            ],
            "media": "https://external-preview.redd.it/lHtWLPS9UUMBsorZBTJ6xp0JeM5Wqip3dF4-wLRWIA8.jpg?auto=webp&s=278700a3cbc09a6cca10978ddc16291b784383b2",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.248744,
            "_id": "11996cd8893e19bf1e40607d2afe50cc"
        },
        {
            "title": "What's the Difference Between a Bitcoin Wallet and an Exchange?",
            "author": "Chris Hoffman",
            "published_date": "2022-03-13 22:00:00",
            "published_date_precision": "full",
            "link": "https://www.howtogeek.com/347464/whats-the-difference-between-a-bitcoin-wallet-and-an-exchange",
            "clean_url": "howtogeek.com",
            "excerpt": "A Bitcoin wallet is basically a software program in which you store Bitcoin. An exchange lets you convert 'real money' like US dollars to Bitcoin. Exchanges also provide a wallet—but you don't…",
            "summary": "A Bitcoin wallet is basically a software program in which you store Bitcoin. An exchange lets you convert 'real money' like US dollars to Bitcoin. Exchanges also provide a wallet—but you don't necessarily have full control of that wallet.\nWe're not recommending you invest in Bitcoin. But, if you're putting money into Bitcoin—or you're just interested in how it works—you should know this stuff. What Is a Bitcoin Wallet?\n\nSo, we mentioned before that a Bitcoin wallet is a software program in which you store Bitcoin.",
            "rights": "howtogeek.com",
            "rank": 1126,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Chris Hoffman"
            ],
            "media": "https://www.howtogeek.com/wp-content/uploads/2018/03/img_5abc362ce7021.jpg?height=200p&trim=2,2,2,2",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.240061,
            "_id": "086ef78452de2464fecfba2c784030fb"
        },
        {
            "title": "Bitcoin 2022 Is At The Center Of Something Much Bigger Happe...",
            "author": null,
            "published_date": "2022-03-14 20:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://menafn.com/1103845340/Bitcoin-2022-Is-At-The-Center-Of-Something-Much-Bigger-Happening-Globally&source=26",
            "clean_url": "menafn.com",
            "excerpt": "Miami, FL | March 14, 2022 09:53 AM Eastern Daylight Time",
            "summary": "(MENAFN- News Direct)\n\nMiami, FL | March 14, 2022 09:53 AM Eastern Daylight Time\n\nEducation, Celebration, Hyperbitcoinization\n\nBitcoin Week exists beyond the Bitcoin Conference as a powerful part of the broader movement towards hyperbitcoinization.\n\n21MillonesBTC.com is excited to see Miami Beach as the center of Bitcoin Week 2022 and is happy to not only participate but also contribute so that the Hispanic community in South Florida and Latin America can be represented. You will not only learn about the Bitcoin ecosystem of companies and projects in the conference (including amazing speakers ) but also access content in Spanish (some articles and white papers will be translated to Spanish by 21MillonesBTC.",
            "rights": "menafn.com",
            "rank": 7126,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://menafn.com/updates/pr/2022-03/14/ND_90da7image_story.png",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.238262,
            "_id": "754d5bc1ce5e6c515f4516117a86b72b"
        },
        {
            "title": "Bitcoin Investment Tips for the Beginners",
            "author": null,
            "published_date": "2022-03-08 14:37:25",
            "published_date_precision": "full",
            "link": "http://www.tmcnet.com/topics/articles/2022/03/08/451740-bitcoin-investment-tips-the-beginners.htm",
            "clean_url": "tmcnet.com",
            "excerpt": "Bitcoin is not like other currencies. Bitcoin isn't really even a 'currency' at all. Bitcoin is fundamentally different from 'fiat currencies.' Bitcoin was designed to be an entirely new system of money and payments, separate and distinct from the fiat Dollar, Yen, Euro, etc. If you want to earn the bulk amount of profit through bitcoin investment then Meta Profit is an authentic platform that can help you in this regard.",
            "summary": "March 08, 2022\n\nBitcoin is not like other currencies. Bitcoin isn't really even a 'currency' at all. Bitcoin is fundamentally different from 'fiat currencies.' Bitcoin was designed to be an entirely new system of money and payments, separate and distinct from the fiat Dollar, Yen, Euro, etc. If you want to earn the bulk amount of profit through bitcoin investment then Meta Profit is an authentic platform that can help you in this regard.\n\n\n\n\n\n\n\nBitcoin is decentralised; Bitcoin cannot be brought down by any one individual or group of individuals that could be thwarted by corrupt governments or any outside influences.",
            "rights": "tmcnet.com",
            "rank": 3926,
            "topic": "tech",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://images.tmcnet.com/tmc/misc/articles/image/2022-mar/9933602641-crypto-bitcoin.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.227199,
            "_id": "126e9afa6c4e906e6dc7e0ef0b0391f8"
        },
        {
            "title": "How to get rich with bitcoin even if (1)",
            "author": "KhakiJabir@slideshare.net(KhakiJabir)",
            "published_date": "2022-03-14 19:25:14",
            "published_date_precision": "full",
            "link": "https://www.slideshare.net/KhakiJabir/how-to-get-rich-with-bitcoin-even-if-1-251347384",
            "clean_url": "slideshare.net",
            "excerpt": "1. \"How To Get Rich With Bitcoin Even If You Have No Clue About Technology\" The surprising wealth-building secret of a globe-trotting vagabond Dear Investor, click this link to be rich:…",
            "summary": "1. \"How To Get Rich With Bitcoin Even If You Have No Clue About Technology\"\nThe surprising wealth-building secret of a\nglobe-trotting vagabond\nDear Investor,\nclick this link to be rich: https://bit.ly/3q501W9\nI'm writing this letter to dispel a popular myth: Many investors believe it's already too late to make a\nlot of money with Bitcoin.\nNothing could be further from the truth.\nHere's why:\nThe incredible story of how I missed the boat on Bitcoin,still got rich, and how you can do the\nsame...\nThe year is 2009.",
            "rights": "slideshare.net",
            "rank": 108,
            "topic": "news",
            "country": "unknown",
            "language": "en",
            "authors": [
                "KhakiJabir"
            ],
            "media": "https://cdn.slidesharecdn.com/ss_thumbnails/howtogetrichwithbitcoinevenif1-220314192514-thumbnail-4.jpg?cb=1647286241",
            "is_opinion": false,
            "twitter_account": "@slideshare",
            "_score": 9.223722,
            "_id": "512692ba8988ebe849092fb4d2077f75"
        },
        {
            "title": "Forbes: \"It's time for the UK's top financial regulator to ditch the puerile language about bitcoin, and to remember whose interests it has a statutory obligation to protect.\" : Bitcoin",
            "author": "/u/Eastern_Description2",
            "published_date": "2022-03-14 13:27:40",
            "published_date_precision": "full",
            "link": "https://www.reddit.com/r/Bitcoin/comments/tdxhu8/forbes_its_time_for_the_uks_top_financial",
            "clean_url": "reddit.com",
            "excerpt": "submitted by /u/Eastern_Description2 [link] [comments]",
            "summary": "Bitcoin is the currency of the Internet: a distributed, worldwide, decentralized digital money. Unlike traditional currencies such as dollars, bitcoins are issued and managed without any central authority whatsoever: there is no government, company, or bank in charge of Bitcoin. As such, it is more resistant to wild inflation and corrupt banks. With Bitcoin, you can be your own bank.",
            "rights": "reddit.com",
            "rank": 38,
            "topic": "finance",
            "country": "US",
            "language": "en",
            "authors": [
                "/u/Eastern_Description2"
            ],
            "media": "https://external-preview.redd.it/MFC_ZJVYLpRbRcmtR6Gs5bHLQhCfCoznh7IJMXFyVqQ.jpg?auto=webp&s=fd07f7d8542405d59ed2fc2870e031eee88a0fd4",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.223336,
            "_id": "92387654216093de9fc8bd24a1b02f0a"
        },
        {
            "title": "The Questionable Ethics Of Anti-Bitcoin ESG Junk-Science",
            "author": "Tyler Durden",
            "published_date": "2022-03-14 07:30:00",
            "published_date_precision": "full",
            "link": "https://www.zerohedge.com/crypto/questionable-ethics-anti-bitcoin-esg-junk-science",
            "clean_url": "zerohedge.com",
            "excerpt": "Bitcoin environmental concerns are often portrayed in misleading and exaggerated ways contrary to proper research.",
            "summary": "Authored by 'Level39' via Bitcoin Magazine,Bitcoin environmental concerns are often portrayed in misleading and exaggerated ways contrary to proper research...Bitcoin receives disproportionate media coverage over its tiny fraction of a percent of global emissions and relatively inconsequential environmental impact. Why this happens requires following the money into environmental, social and corporate governance (ESG) accounting. ESG accountants appear to be using Bitcoin's open, transparent ledger — that can be audited by anyone in the world in real time — to exaggerate Bitcoin's impact on the environment, with shoddy science, while profiting from the very fears they provoke.",
            "rights": "zerohedge.com",
            "rank": 2009,
            "topic": "news",
            "country": "BG",
            "language": "en",
            "authors": [
                "Tyler Durden"
            ],
            "media": "https://assets.zerohedge.com/s3fs-public/styles/16_9_max_700/public/2022-03/2022-03-13_10-09-14.jpg?itok=fhQpuotC",
            "is_opinion": false,
            "twitter_account": "@zerohedge",
            "_score": 9.204054,
            "_id": "33d44618c477e3b39f6e957623c4262a"
        },
        {
            "title": "Bitcoin City of El Salvador $1 Billion Bond Sale to Start by 20 March",
            "author": "Matti Williamson",
            "published_date": "2022-03-14 12:33:42",
            "published_date_precision": "full",
            "link": "https://www.financemagnates.com/cryptocurrency/el-salvador-bitcoin-city-1-billion-bond-sale-to-start-by-20-march-2022-via-liquid-network",
            "clean_url": "financemagnates.com",
            "excerpt": "El Salvador's $1 billion Bitcoin bond may be issued between 14 and 20 March. The 10-year bond will offer +6.5% per annum for 10 years (around +$1.65 billion).",
            "summary": "El Salvador's $1 billion Bitcoin bond may be issued between 14 and 20 March. The 10-year bond will offer +6.5% per annum for 10 years (approximately +$1.65 billion).$500 million will be used to buy bitcoins, the remaining $500 million will be spent on Bitcoin mining infrastructure as part of 'Bitcoin City'. Q4 2021 volumes have gone up or down and how much? The Finance Minister, Alejandro Zelaya said, \"We believe that between March 15 and 20 is the right timing, we have the tools almost finished.",
            "rights": "financemagnates.com",
            "rank": 9126,
            "topic": "finance",
            "country": "IL",
            "language": "en",
            "authors": [
                "Matti Williamson"
            ],
            "media": "https://images.financemagnates.com/images/El%20Salvador%20Bitcoin%20bond_id_9a1d79b4-e2fd-42af-b7ff-d956111b7a9b_size900.jpg",
            "is_opinion": false,
            "twitter_account": "@financemagnates",
            "_score": 9.200402,
            "_id": "46fda2de0ac0bd12829559218bd856d3"
        },
        {
            "title": "‘I Won't Sell'—Tesla Billionaire Elon Musk Issues Inflation Advice As The Price Of His Bitcoin, Ethereum And Dogecoin Plummet",
            "author": "Billy Bambrough, Senior Contributor",
            "published_date": "2022-03-14 06:30:30",
            "published_date_precision": "full",
            "link": "https://www.forbes.com/sites/billybambrough/2022/03/14/i-wont-sell-tesla-billionaire-elon-musk-issues-inflation-advice-as-the-price-of-his-bitcoin-ethereum-and-dogecoin-plummet",
            "clean_url": "forbes.com",
            "excerpt": "Tesla billionaire Elon Musk has said he still owns and \"won't sell\" his bitcoin, ethereum and dogecoin—advising people not to hold dollars when inflation is high...",
            "summary": "Bitcoin and cryptocurrency prices have been under pressure through most of 2022, with the bitcoin price losing almost 20% so far this year. Subscribe now to Forbes' CryptoAsset & Blockchain Advisor and successfully navigate the latest crypto price crash The ethereum price and other major cryptocurrencies have also fallen sharply as bullish investors balk at the prospect of rising interest rates and a slow down in pandemic-era stimulus measures. Now, Tesla billionaire Elon Musk, who sent shockwaves through the crypto world when he added $1.",
            "rights": "Copyright 2022 Forbes Media LLC",
            "rank": 51,
            "topic": "business",
            "country": "US",
            "language": "en",
            "authors": [
                "Billy Bambrough, Senior Contributor",
                "Billy Bambrough, Senior Contributor"
            ],
            "media": "https://imageio.forbes.com/specials-images/imageserve/60c64fa7ab58a662f3764dfa/0x0.jpg?format=jpg&width=1200&fit=bounds",
            "is_opinion": false,
            "twitter_account": "@forbes",
            "_score": 9.200018,
            "_id": "2a6d63c42eebd5c8ef214708684c07bb"
        },
        {
            "title": "Bitcoin Getting Under People's Skin as Popular Tattoo",
            "author": "Rob Lenihan",
            "published_date": "2022-03-14 13:54:40",
            "published_date_precision": "full",
            "link": "https://www.thestreet.com/investing/cryptocurrency/bitcoin-getting-under-peoples-skin-as-popular-tattoo",
            "clean_url": "thestreet.com",
            "excerpt": "There was a 222% increase in searches for 'crypto tattoo' in the past year",
            "summary": "Bitcoin has been getting a lot of ink lately.And we're not talking about news coverage. 'Bitcoin tattoo turned out sick'The world's largest cryptocurrency by market cap has been making its mark on the tattoo scene, according to research by Crypto Head.The firm found the most tattooed cryptocurrency, with #bitcointattoo recently racking up 986 posts on Instagram as people show their love for bitcoin by putting its symbol onto their bodies.Coming in behind bitcoin was #cryptotattoo with 956 posts, followed by #dogecointattoo with 11 Instagram posts and #ethereumtattoo with six.",
            "rights": "thestreet.com",
            "rank": 1376,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Rob Lenihan"
            ],
            "media": "https://www.thestreet.com/.image/t_share/MTg1ODg4NTIzOTg1ODg4OTYz/bitcoin_2.jpg",
            "is_opinion": false,
            "twitter_account": "@thestreet",
            "_score": 9.188779,
            "_id": "003d5d112ad867bad43231a7bf6ad849"
        },
        {
            "title": "Bitcoin Market Share,Size 2022 Global Statistics, Growth Factors, Industry Trends, Competition Strategies, Revenue Analysis, Key Players, Regional Analysis by Forecast to 2027",
            "author": "TheExpressWire",
            "published_date": "2022-03-08 09:07:37",
            "published_date_precision": "full",
            "link": "https://www.digitaljournal.com/pr/bitcoin-market-sharesize-2022-global-statistics-growth-factors-industry-trends-competition-strategies-revenue-analysis-key-players-regional-analysis-by-forecast-to-2027",
            "clean_url": "digitaljournal.com",
            "excerpt": "Bitcoin market research study provides a basic summary of the industry such as definitions, applications, classifications, and industry chain structure. The Global Bitcoin market analysis is offered…",
            "summary": "Bitcoin market research study provides a basic summary of the industry such as definitions, applications, classifications, and industry chain structure. The Global Bitcoin market analysis is offered for the global markets such as competitive landscape analysis, development trends, and major regions growth status.\n\nGlobal Bitcoin Market provides In-Depth analysis on the market status of the Bitcoin manufacturers with best facts and figures, overview, definition, SWOT analysis, expert opinions and the latest developments across the globe.",
            "rights": "digitaljournal.com",
            "rank": 1610,
            "topic": "economics",
            "country": "CA",
            "language": "en",
            "authors": [
                "Dr. Tim Sandle",
                "Written By"
            ],
            "media": "https://secure.gravatar.com/avatar/a5936643cfb93345023945704b62c134?s=150&d=blank&r=pg",
            "is_opinion": false,
            "twitter_account": "@digitaljournal",
            "_score": 9.168457,
            "_id": "5bb8d4ca4e9ae6d49753d805837b290b"
        },
        {
            "title": "What Does The Future Hold For Bitcoin Mining? : Bitcoin",
            "author": "/u/alexyslang",
            "published_date": "2022-03-14 00:23:15",
            "published_date_precision": "full",
            "link": "https://www.reddit.com/r/Bitcoin/comments/tdkm7f/what_does_the_future_hold_for_bitcoin_mining",
            "clean_url": "reddit.com",
            "excerpt": "submitted by /u/alexyslang [link] [comments]",
            "summary": "Bitcoin is the currency of the Internet: a distributed, worldwide, decentralized digital money. Unlike traditional currencies such as dollars, bitcoins are issued and managed without any central authority whatsoever: there is no government, company, or bank in charge of Bitcoin. As such, it is more resistant to wild inflation and corrupt banks. With Bitcoin, you can be your own bank.",
            "rights": "reddit.com",
            "rank": 38,
            "topic": "finance",
            "country": "US",
            "language": "en",
            "authors": [
                "/u/alexyslang"
            ],
            "media": "https://external-preview.redd.it/fIyO6xxHYlsAxZs4wbBIFzEvyq4Xh0h2jBLHOaeH5jE.jpg?auto=webp&s=1e2e10bee2f4b0f6b46852c45d77b37eb0aec56a",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.164995,
            "_id": "9967896376db54be696de5d69bf7b0a8"
        },
        {
            "title": "How El Salvador Is Fixing Chivo Wallet, Trying To Get Bitcoin Adoption Back On Track",
            "author": "Jaime Garcia",
            "published_date": "2022-03-14 14:44:09",
            "published_date_precision": "full",
            "link": "https://bitcoinmagazine.com/business/el-salvador-fixing-chivo-bitcoin-wallet",
            "clean_url": "bitcoinmagazine.com",
            "excerpt": "El Salvador tapped crypto software firm AlphaPoint to fix numerous problems with its state Chivo wallet and help citizens adopt Bitcoin.",
            "summary": "When Bitcoin became legal tender in El Salvador, thousands of keen Salvadorans awaited to download the country's government-furnished Bitcoin wallet, Chivo. However, within hours, it became clear that the hyperbitcoinization process would not be painless, as users experienced download delays, challenges in the identity verification process and problems transacting over the Lightning Network with Chivo. Chivo's challenges became even more pronounced as El Salvador held the Adopting Bitcoin and The Latin America Bitcoin & Blockchain conferences, and many international Bitcoiners attempted to transact with Chivo.",
            "rights": "bitcoinmagazine.com",
            "rank": 8458,
            "topic": "business",
            "country": "US",
            "language": "en",
            "authors": [
                "Jaime Garcia"
            ],
            "media": "https://bitcoinmagazine.com/.image/t_share/MTg4MDYxNjM3MzE0MzU3MDM0/how-el-salvador-is-fixing-chivo-wallet-trying-to-get-bitcoin-adoption-back-on-track.png",
            "is_opinion": false,
            "twitter_account": "@JaimeWGarcia",
            "_score": 9.155961,
            "_id": "379b670eca7caa39a2a905db0bb8a577"
        },
        {
            "title": "Someone Just Sent $49M In Bitcoin Onto Coinbase",
            "author": "Benzinga Insights",
            "published_date": "2022-03-14 17:02:00",
            "published_date_precision": "full",
            "link": "https://www.benzinga.com/markets/cryptocurrency/22/03/26126952/someone-just-sent-49m-in-bitcoin-onto-coinbase",
            "clean_url": "benzinga.com",
            "excerpt": "What happened: An anonymous cryptocurrency wallet holding $49,231,532 of Bitcoin (CRYPTO:",
            "summary": "What happened: An anonymous cryptocurrency wallet holding $49,231,532 of Bitcoin (CRYPTO: BTC) just transferred their funds onto Coinbase. The bitcoin wallet address tied to this transfer has been identified as:\n1KHwtS5mn7NMUm7Ls7Y1XwxLqMriLdaGbX\nYou can view more details about the transaction here.\nWhy it matters: Cryptocurrency transfers from wallets to exchanges is typically a bearish signal. Most high networth cryptocurrency traders hold their funds on a hardware wallet, as these devices offer better security than cryptocurrency exchanges.",
            "rights": "benzinga.com",
            "rank": 2282,
            "topic": "finance",
            "country": "US",
            "language": "en",
            "authors": [
                "Benzinga Insights"
            ],
            "media": "https://cdn2.benzinga.com/files/imagecache/og_image_social_share_1200x630/images/story/2022/btc_whale_image_176.png?width=720",
            "is_opinion": false,
            "twitter_account": "@benzinga",
            "_score": 9.135863,
            "_id": "bbfed31d69a2aec605bbe4663db8be82"
        },
        {
            "title": "Bitcoin: Relief Rally Then Dip (Cryptocurrency:BTC-USD)",
            "author": null,
            "published_date": "2022-03-11 04:59:02",
            "published_date_precision": "full",
            "link": "https://seekingalpha.com/article/4494733-bitcoin-relief-rally-then-dip",
            "clean_url": "seekingalpha.com",
            "excerpt": "Bitcoin has room to move lower as the outlook for traditional markets looks bearish. How much lower will Bitcoin go? What will drive movement? Find out?",
            "summary": "Tevarak/iStock via Getty Images In hindsight, the laser eyes were Bitcoin's (BTC-USD) top signal. Laser eyes top (Google Trends) Bitcoin is still young and competing against multi-century monetary premiums held by gold (GLD), bonds, and fiat currencies. As a result, Bitcoin is currently more correlated to the NASDAQ (QQQ) than it is to gold. For Bitcoin to increase or maintain stability in an uncertain market, investors need to shift to view Bitcoin as a hard asset rather than a speculative investment.",
            "rights": "seekingalpha.com",
            "rank": 951,
            "topic": "finance",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://static.seekingalpha.com/cdn/s3/uploads/getty_images/1320532557/image_1320532557.jpg?io=getty-c-w750",
            "is_opinion": false,
            "twitter_account": "@SeekingAlpha",
            "_score": 9.123953,
            "_id": "96528f52fd7284a56830eb55dbfb2d68"
        },
        {
            "title": "Bitcoin Loan Market Size 2022 Global Competitors Strategy, Industry Trends, Segments, Regional Analysis, Review, Key Players Profile, Statistics and Growth to 2027 Analysis",
            "author": "TheExpressWire",
            "published_date": "2022-03-08 09:07:37",
            "published_date_precision": "full",
            "link": "https://www.digitaljournal.com/pr/bitcoin-loan-market-size-2022-global-competitors-strategy-industry-trends-segments-regional-analysis-review-key-players-profile-statistics-and-growth-to-2027-analysis",
            "clean_url": "digitaljournal.com",
            "excerpt": "Bitcoin Loan Market report covers the manufacturers' data, including business distribution, cost and price, margin, and gross revenue. This allows a reader to understand consumers' behavior and a…",
            "summary": "Bitcoin Loan Market report covers the manufacturers' data, including business distribution, cost and price, margin, and gross revenue. This allows a reader to understand consumers' behavior and a better understanding of the leading competitor's operation in the market.\n\nGlobal Bitcoin Loan Market includes Elaborative company profiling of leading players of the Bitcoin Loan market. All of the segments studied in the report are analyzed based on different factors such as market share, revenue, and CAGR.",
            "rights": "digitaljournal.com",
            "rank": 1610,
            "topic": "economics",
            "country": "CA",
            "language": "en",
            "authors": [
                "Dr. Tim Sandle",
                "Written By"
            ],
            "media": "https://secure.gravatar.com/avatar/a5936643cfb93345023945704b62c134?s=150&d=blank&r=pg",
            "is_opinion": false,
            "twitter_account": "@digitaljournal",
            "_score": 9.114232,
            "_id": "fb35a0077cfac7d34a8bafd7be836c24"
        },
        {
            "title": "Bitcoin Is Insurance Against A State Gone Rogue",
            "author": "Tyler Durden",
            "published_date": "2022-03-14 22:20:00",
            "published_date_precision": "full",
            "link": "https://www.zerohedge.com/crypto/bitcoin-insurance-against-state-gone-rogue",
            "clean_url": "zerohedge.com",
            "excerpt": "Immutable value storage via Bitcoin is our best defense against tyrannical overreaching governments...",
            "summary": "Monday, Mar 14, 2022 - 10:20 PMAuthored by Josef Tetek via Bitcoin Magazine,Immutable value storage via Bitcoin is our best defense against tyrannical overreaching governments.\"It would have been nice to get this attention in any other context. WikiLeaks has kicked the hornet's nest, and the swarm is headed towards us.\"- Satoshi NakamotoA clash between Bitcoiners and the establishment has been around the corner for a long time. Satoshi's quote above illustrates a common concern over the inevitable conflict: we all wish for the masses to first learn about Bitcoin as the neutral money that it is, not as a tool that aids potentially controversial causes.",
            "rights": "zerohedge.com",
            "rank": 2009,
            "topic": "news",
            "country": "BG",
            "language": "en",
            "authors": [
                "Tyler Durden"
            ],
            "media": "https://assets.zerohedge.com/s3fs-public/styles/16_9_max_700/public/2022-03/2022-03-14_13-27-39.png?itok=7Qnon8IN",
            "is_opinion": false,
            "twitter_account": "@zerohedge",
            "_score": 9.102504,
            "_id": "cc42cb8a6303d8a0e7102fcfa4651749"
        },
        {
            "title": "What is Bitcoin?",
            "author": "Mark Smith",
            "published_date": "2022-03-08 16:45:04",
            "published_date_precision": "full",
            "link": "https://www.livescience.com/bitcoin-definition",
            "clean_url": "livescience.com",
            "excerpt": "Bitcoin is a virtual 'cryptocurrency' traded much like real money.",
            "summary": "Bitcoin is a virtual currency known as a 'cryptocurrency that can be traded between buyers and sellers much like \"real\" money is. One of the very first and most high-profile cryptocurrencies launched, Bitcoin is also the most well-known of this virtual money. Bitcoin first emerged in 2009 and its creator is allegedly called Satoshi Nakamoto, though several theories exist as to Nakamoto's real identity, according to Business Insider. A bitcoin is essentially a digital computer file that is stored in something called a digital wallet, which can be accessed by software and apps.",
            "rights": "livescience.com",
            "rank": 461,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Mark Smith"
            ],
            "media": "https://cdn.mos.cms.futurecdn.net/msJ7bDf5nyPJ6CMbg4LwfE-1200-80.png",
            "is_opinion": false,
            "twitter_account": "@LiveScience",
            "_score": 9.096311,
            "_id": "6ead6af57d081beab7bea8400350e82d"
        },
        {
            "title": "BTC Inc Gives Black Bitcoin Billionaire Members $100,000 Worth Of Bitcoin 2022 Conference Tickets",
            "author": "Shawn Amick",
            "published_date": "2022-03-09 10:28:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.nasdaq.com/articles/btc-inc-gives-black-bitcoin-billionaire-members-%24100000-worth-of-bitcoin-2022-conference",
            "clean_url": "nasdaq.com",
            "excerpt": "BTC Inc is giving away 100 tickets, totaling a value of $100,000 to members of Black Bitcoin Billionaire for the Bitcoin 2022 conference.",
            "summary": "BTC Inc is giving away 100 tickets, totaling a value of $100,000 to members of Black Bitcoin Billionaire for the Bitcoin 2022 conference.\n\n$100,000 in tickets will be given to the Black Bitcoin Billionaire members for Bitcoin 2022.\n\nThe three-day general admission passes will be awarded to a lottery made up of supporters of Black Bitcoin Billionaire who have purchased merchandise this past year.\n\n'Bitcoin is not just a monetary technology, but a cultural movement,' says BTC Inc CEO, David Bailey.",
            "rights": "nasdaq.com",
            "rank": 870,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Shawn Amick"
            ],
            "media": "https://www.nasdaq.com/sites/acquia.prod/files/bitcoin_magazine/img_5425.jpg?136223615",
            "is_opinion": false,
            "twitter_account": "@Nasdaq",
            "_score": 9.093262,
            "_id": "f9781bbeb181bf4dcd31236aab9f862b"
        },
        {
            "title": "Unified MMA Pays Fight Purse With the Bitcoin Well Corporate Bitcoin Savings Plan",
            "author": null,
            "published_date": "2022-03-09 11:59:57",
            "published_date_precision": "full",
            "link": "https://financialpost.com/globe-newswire/unified-mma-pays-fight-purse-with-the-bitcoin-well-corporate-bitcoin-savings-plan",
            "clean_url": "financialpost.com",
            "excerpt": "This advertisement has not loaded yet, but your article continues below. EDMONTON, Alberta, March 09, 2022 (GLOBE NEWSWIRE) — Bitcoin Well Inc. ('Bitcoin Well') (TSXV: BTCW), a technology company…",
            "summary": "This advertisement has not loaded yet, but your article continues below. EDMONTON, Alberta, March 09, 2022 (GLOBE NEWSWIRE) — Bitcoin Well Inc. ('Bitcoin Well') (TSXV: BTCW), a technology company building and utilizing products that offer safe and easy ways to buy, sell and use Bitcoin, is pleased to announce that Unified MMA has joined the Bitcoin Well, Corporate Bitcoin Savings Plan ('BSP'). This will enable the organization to offer fighters the opportunity to take a portion of their fight purse in bitcoin.",
            "rights": "financialpost.com",
            "rank": 1902,
            "topic": "energy",
            "country": "CA",
            "language": "en",
            "authors": [],
            "media": "https://www.globenewswire.com/newsroom/ti?nf=ODQ5OTY1OSM0Nzc4Mzc2IzIyMDI1MzE=",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.084114,
            "_id": "d0e181e5497ec58449dad0c2e5aa2671"
        },
        {
            "title": "Unified MMA Pays Fight Purse With the Bitcoin Well Corporate Bitcoin Savings Plan",
            "author": "Bitcoin Well",
            "published_date": "2022-03-09 00:00:00",
            "published_date_precision": "date",
            "link": "https://www.globenewswire.com/news-release/2022/03/09/2399755/0/en/Unified-MMA-Pays-Fight-Purse-With-the-Bitcoin-Well-Corporate-Bitcoin-Savings-Plan.html",
            "clean_url": "globenewswire.com",
            "excerpt": "EDMONTON, Alberta, March 09, 2022 (GLOBE NEWSWIRE) -- Bitcoin Well Inc. ('Bitcoin Well') (TSXV: BTCW), a technology company building and utilizing...",
            "summary": "EDMONTON, Alberta, March 09, 2022 (GLOBE NEWSWIRE) -- Bitcoin Well Inc. ('Bitcoin Well') (TSXV: BTCW), a technology company building and utilizing products that offer safe and easy ways to buy, sell and use Bitcoin, is pleased to announce that Unified MMA has joined the Bitcoin Well, Corporate Bitcoin Savings Plan ('BSP'). This will enable the organization to offer fighters the opportunity to take a portion of their fight purse in bitcoin. Shane Campbell, winner of the Unified 43 Super Lightweight Bout opted to receive a portion of his winnings in bitcoin, via the BSP.",
            "rights": "globenewswire.com",
            "rank": 610,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Bitcoin Well"
            ],
            "media": "https://ml.globenewswire.com/Resource/Download/853216c4-d783-4890-85f0-82ff55e09523?size=1",
            "is_opinion": false,
            "twitter_account": "globenewswire",
            "_score": 9.082394,
            "_id": "d22ef929b9707c99ee23d9896bf73026"
        },
        {
            "title": "Bitcoin Cash price analysis: Bullish momentum uplifts price to $294. More gains ahead?",
            "author": "folly",
            "published_date": "2022-03-14 14:30:00",
            "published_date_precision": "timezone unknown",
            "link": "https://article.wn.com/view/2022/03/13/Bitcoin_Cash_price_analysis_Bullish_momentum_uplifts_price_t",
            "clean_url": "wn.com",
            "excerpt": "Photo: Creative Commons TL;DR Breakdown Bitcoin Cash price analysis is bullish.Price has increased up to $294.4.Support for BCH/USD is present at $286. The Bitcoin cash price analysis is bullish for…",
            "summary": "Photo: Creative Commons TL;DR Breakdown Bitcoin Cash price analysis is bullish.Price has increased up to $294.4.Support for BCH/USD is present at $286. The Bitcoin cash price analysis is bullish for the day as the price has increased to $294 in the last 24 hours. The bulls have managed to maintain their momentum in a steady... read full story Photo: Bitcoin Cash (BCH) is a hard fork of the cryptocurrency bitcoin.",
            "rights": "wn.com",
            "rank": 2336,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://ecdn9.wn.com/o25/ph/img/11/89/63435c244fa0ba732a3972c908fb-grande.jpg",
            "is_opinion": false,
            "twitter_account": "@worldnewsdotcom",
            "_score": 9.074907,
            "_id": "139914f7e210d6ec819d439804e545d5"
        },
        {
            "title": "Bitcoin mixing service CoinJoin starts blacklisting BTC tied to illegal activity",
            "author": null,
            "published_date": "2022-03-14 12:06:41",
            "published_date_precision": "full",
            "link": "https://www.theblockcrypto.com/post/137668/bitcoin-mixing-service-coinjoin-starts-blacklisting-btc-tied-to-illegal-activity",
            "clean_url": "theblockcrypto.com",
            "excerpt": "CoinJoin has long banned people from using it to mix illegitimate funds. Now it's actively preventing them from doing so.",
            "summary": "Bitcoin mixing service CoinJoin has started blacklisting bitcoin tied to illegal activity in a move derided by some advocates of crypto privacy.\nCoinJoin, a bitcoin mixing service that's part of the privacy-focused Wasabi Wallet, will start blocking bitcoin tagged with certain identifiers, according to an announcement on Sunday.\nMixing services let you obfuscate the transaction history of your coins, allowing users greater privacy but also attracting those seeking to launder stolen bitcoin. The person who hacked Twitter in 2020 and sent out fake giveaway messages from high-profile accounts, for example, sent the loot through CoinJoin, according to blockchain analytics firm Elliptic.",
            "rights": "theblockcrypto.com",
            "rank": 11207,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://www.tbstat.com/wp/uploads/2020/06/20200603_Tornado_Privacy-Daily.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.072161,
            "_id": "df4b7260e6587084f92d335902f473f3"
        },
        {
            "title": "Anonymous Bitcoin Whale Just Moved $20M Worth Of BTC Off Coinbase",
            "author": "Benzinga Insights",
            "published_date": "2022-03-14 17:02:17",
            "published_date_precision": "full",
            "link": "https://www.benzinga.com/markets/cryptocurrency/22/03/26126960/anonymous-bitcoin-whale-just-moved-20m-worth-of-btc-off-coinbase",
            "clean_url": "benzinga.com",
            "excerpt": "What happened: A Bitcoin (CRYPTO: BTC) whale just sent $20,956...",
            "summary": "What happened: A Bitcoin (CRYPTO: BTC) whale just sent $20,956,513 worth of Bitcoin off Coinbase.\nThe BTC address associated with this transaction has been identified as: bc1qdfw3qpdm3f9j0ldg5pmwrwq0ueynme6l8uchs8.\nWhy it matters: Bitcoin 'Whales' (investors who own $10 million or more in BTC) typically send cryptocurrency from exchanges when planning to hold their investments for an extended period of time. Storing large amounts of money on an exchange presents an additional risk of theft, as exchange wallets are the most sought-after target for cryptocurrency hackers.",
            "rights": "benzinga.com",
            "rank": 2282,
            "topic": "finance",
            "country": "US",
            "language": "en",
            "authors": [
                "Benzinga Insights"
            ],
            "media": "https://cdn2.benzinga.com/files/imagecache/og_image_social_share_1200x630/images/story/2022/btc_whale_image_178.png?width=720",
            "is_opinion": false,
            "twitter_account": "@benzinga",
            "_score": 9.067045,
            "_id": "1f2a2634f979ebd057a23be57d2c7a23"
        },
        {
            "title": "Bitcoin Exchanges",
            "author": null,
            "published_date": "2022-03-09 20:05:25",
            "published_date_precision": "full",
            "link": "https://marketbusinessnews.com/bitcoin-exchanges/293133",
            "clean_url": "marketbusinessnews.com",
            "excerpt": "Read this article to learn more about the bitcoin exchanges available and the benefits that these bring for your security.",
            "summary": "Bitcoin is a virtual currency with no ties to a central bank. Bitcoin has been gaining popularity as an alternative way of doing business online, and several websites have sprung up that allow people to pay for things with Bitcoin instead of cash or credit.\nYou can then exchange your Bitcoin for dollars, euros, or other currencies by 'selling' them to someone who wants Bitcoin in return at the current going rate on one site. The whole process costs almost nothing, but you have to be very careful whom you deal with so as not to get ripped off.",
            "rights": "marketbusinessnews.com",
            "rank": 19172,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://marketbusinessnews.com/wp-content/uploads/2022/01/bitcoin-cryptocurrency-g6e2aed9fd_1920.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.064395,
            "_id": "e322e6778499e1f1bf53b332f8dbe3cb"
        },
        {
            "title": "Someone Just Sent 1,112 Bitcoin Onto Coinbase",
            "author": "Benzinga Insights",
            "published_date": "2022-03-14 17:02:05",
            "published_date_precision": "full",
            "link": "https://www.benzinga.com/markets/cryptocurrency/22/03/26126955/someone-just-sent-1-112-bitcoin-onto-coinbase",
            "clean_url": "benzinga.com",
            "excerpt": "What happened: An anonymous cryptocurrency wallet holding $42,132,488 of Bitcoin (CRYPTO:",
            "summary": "What happened: An anonymous cryptocurrency wallet holding $42,132,488 of Bitcoin (CRYPTO: BTC) just transferred their funds onto Coinbase. The bitcoin wallet address tied to this transfer has been identified as:\n14h7kfdUakgwEJbv16N9KoUfgCUBDGFWbj\nYou can view more details about the transaction here.\nWhy it matters: Cryptocurrency transfers from wallets to exchanges is typically a bearish signal. Most high networth cryptocurrency traders hold their funds on a hardware wallet, as these devices offer better security than cryptocurrency exchanges.",
            "rights": "benzinga.com",
            "rank": 2282,
            "topic": "finance",
            "country": "US",
            "language": "en",
            "authors": [
                "Benzinga Insights"
            ],
            "media": "https://cdn2.benzinga.com/files/imagecache/og_image_social_share_1200x630/images/story/2022/btc_whale_image_177.png?width=720",
            "is_opinion": false,
            "twitter_account": "@benzinga",
            "_score": 9.059479,
            "_id": "f79059c2fbd10606ec2b9604748e6c04"
        },
        {
            "title": "Basic Principle of Bitcoin Mining",
            "author": null,
            "published_date": "2022-03-09 20:43:53",
            "published_date_precision": "full",
            "link": "https://marketbusinessnews.com/basic-principle-of-bitcoin-mining/293150",
            "clean_url": "marketbusinessnews.com",
            "excerpt": "Read this article to learn more about the basic principles behind Bitcoin mining and the things to consider for mining.",
            "summary": "A cryptocurrency mining farm in Iceland. The picture shows mainly Zeus scrypt miners. By Marco Krohn (Own work) [CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0)], via Wikimedia CommonsBitcoin mining is the process of generating Bitcoin in a Bitcoin network with the help of Bitcoin miner software. Bitcoin miners are usually large Bitcoin companies or organisations that have invested in Bitcoin hardware. They usually mine Bitcoin on a large scale by forming Bitcoin pools and sharing their processing powers to solve algorithms and thus generate Bitcoins for themselves.",
            "rights": "marketbusinessnews.com",
            "rank": 19172,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://marketbusinessnews.com/wp-content/uploads/2018/01/Bitcoin_Mining_Farm_iceland.png",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.056003,
            "_id": "9e840ed004cd2da0eb65739f42560ec6"
        },
        {
            "title": "Honey, I orange-pilled the kids! BTC children's authors on learning about money",
            "author": "Cointelegraph By Joseph Hall",
            "published_date": "2022-03-10 10:03:49",
            "published_date_precision": "full",
            "link": "https://cointelegraph.com/news/honey-i-orange-pilled-the-kids-btc-children-s-authors-on-learning-about-money",
            "clean_url": "cointelegraph.com",
            "excerpt": "Three Bitcoin children's authors share the keys to teaching about Bitcoin and money, explaining why it's important to do so from a young age.",
            "summary": "Bitcoin is for everyone. That includes teenagers, children, toddlers and even newborns.\n\nWhen these kids grow up, they'll use the Bitcoin (BTC) protocol, so it 'makes sense to start to integrate Bitcoin into learning as early as possible.'\n\nAt least, that's according to Scott Sibley, one-half of the couple behind the creation of the Shamory Bitcoin game and the ‘Goodnight Bitcoin' children's bedtime book. He joins a growing list of Bitcoin children's book authors who care deeply about educating children on Bitcoin and money.",
            "rights": "cointelegraph.com",
            "rank": 1910,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Cointelegraph By Joseph Hall"
            ],
            "media": "https://images.cointelegraph.com/images/1200_aHR0cHM6Ly9zMy5jb2ludGVsZWdyYXBoLmNvbS91cGxvYWRzLzIwMjItMDMvYzIzNjk0ZTQtZmFjNC00MTBjLTkxY2EtNmUxYTVmNmZiM2M0LmpwZw==.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.055429,
            "_id": "f34389cee8460c820ec2e66c60c956ce"
        },
        {
            "title": "Get Ready For The Bitcoin Russia Freeze (BTC-USD)",
            "author": null,
            "published_date": "2022-03-14 16:51:07",
            "published_date_precision": "full",
            "link": "https://seekingalpha.com/article/4495312-get-ready-for-bitcoin-russia-freeze",
            "clean_url": "seekingalpha.com",
            "excerpt": "Governments may freeze Bitcoin to enforce Russian sanctions. Look more closely at the Biden Executive Order on crypto. Find out why I'm bearish on BTC-USD.",
            "summary": "Olemedia/E+ via Getty ImagesIn my previous article on Bitcoin (BTC-USD) I highlighted how the Canadian government had effectively shut down the argument over the 'future of money'. In my weekly subscriber service, I picked March 7th for the BTC low and the low in the Dow. Bitcoin worked perfectly and stocks were a day later. I am now expecting governments to freeze trading in BTC using Russia as an excuse. In this article, I will discuss more and try to predict the date using my proprietary model.",
            "rights": "seekingalpha.com",
            "rank": 951,
            "topic": "finance",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://static.seekingalpha.com/cdn/s3/uploads/getty_images/1320779972/image_1320779972.jpg?io=getty-c-w750",
            "is_opinion": false,
            "twitter_account": "@SeekingAlpha",
            "_score": 9.0510845,
            "_id": "7ba49919cec1e7ee173d5570cd714dcf"
        },
        {
            "title": "Okcoin Announces $165M \"Bitcoin Odyssey\" Collective, Partners with Top Venture Firms to Supercharge Bitcoin Adoption",
            "author": "Okcoin",
            "published_date": "2022-03-10 16:39:00",
            "published_date_precision": "full",
            "link": "https://www.prnewswire.com/news-releases/okcoin-announces-165m-bitcoin-odyssey-collective-partners-with-top-venture-firms-to-supercharge-bitcoin-adoption-301500256.html",
            "clean_url": "prnewswire.com",
            "excerpt": "/PRNewswire/ -- Okcoin, one of the world's largest and fastest-growing cryptocurrency platforms, along with the Stacks Accelerator and Stacks Foundation, today...",
            "summary": "SAN FRANCISCO, March 10, 2022 /PRNewswire/ -- Okcoin, one of the world's largest and fastest-growing cryptocurrency platforms, along with the Stacks Accelerator and Stacks Foundation, today announced the launch of the Bitcoin Odyssey, a year-long pledge among venture firms to deploy $165 million collectively into solutions for accelerating bitcoin adoption. The participating firms—which include Digital Currency Group, GSR, and White Star Capital, among others—will allocate capital and resources to projects being built on Stacks, an open-source network for Bitcoin-based smart contracts, as well as the Bitcoin blockchain itself.",
            "rights": "prnewswire.com",
            "rank": 216,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Okcoin"
            ],
            "media": "https://www.prnewswire.com/content/dam/prnewswire/icons/2019-Q4-PRN-Icon-32-32.png",
            "is_opinion": false,
            "twitter_account": "@PRNewswire",
            "_score": 9.046585,
            "_id": "652b102b2f17dc9199bf4e3b23fadc56"
        },
        {
            "title": "Bitcoin Price Prediction 2022-2025",
            "author": "Analytics Insight is an influential platform dedicated to insights, trends, and opinions from the world of data-driven technologies. It monitors developments, recognition, and achievements made by Artificial Intelligence, Big Data and Analytics companies across the globe.",
            "published_date": "2022-03-14 05:40:25",
            "published_date_precision": "full",
            "link": "https://www.analyticsinsight.net/bitcoin-price-prediction-2022-2025",
            "clean_url": "analyticsinsight.net",
            "excerpt": "If you're not sure whether investing in cryptocurrencies is worth it, take a look at our Bitcoin price prediction for the 2022-2025 period.",
            "summary": "by Analytics Insight \nMarch 14, 2022\nBitcoin has been around since 2009, and it's had a wild ride. Some think that its price will continue to rise, while others believe that its bubble is about to burst. In this blog, we'll go over Bitcoin price prediction for 2022-2025 and give you our thoughts on the matter. Don't forget that this is only an estimate, meaning things could change drastically over the next few years. With that being said, let's take a closer look at Bitcoin's future!>>> Find Bitcoin on eToro<<\n>> Find Bitcoin on eToro<<\n>> Find Bitcoin on eToro<<\n>> Find Bitcoin on eToro<<\n>> Find Bitcoin on eToro<<\n>> Find Bitcoin on eToro<<\n>> Find Bitcoin on eToro<<\n>>Find Lucky Block on PancakeSwap Now<<\n>>Find Lucky Block on PancakeSwap Now<<\n>>Find Lucky Block on PancakeSwap Now<<<Cryptocurrency markets are highly volatile and your investments are at risk.",
            "rights": "analyticsinsight.net",
            "rank": 25672,
            "topic": "news",
            "country": "CA",
            "language": "en",
            "authors": [
                "Analytics Insight"
            ],
            "media": "https://analyticsinsight.b-cdn.net/wp-content/uploads/2022/03/Bitcoinq.jpg",
            "is_opinion": false,
            "twitter_account": "@analyticsinme",
            "_score": 9.040144,
            "_id": "7b370ea5af2f8a8731543bdb1a80646e"
        },
        {
            "title": "Bill Gross, 'King of Bonds' and Prominent Crypto Critic, Invests in Bitcoin",
            "author": "Luc Olinga",
            "published_date": "2022-03-14 20:36:19",
            "published_date_precision": "full",
            "link": "https://www.thestreet.com/investing/cryptocurrency/king-of-bonds-bill-gross-a-famous-crypto-critic-invests-in-bitcoin",
            "clean_url": "thestreet.com",
            "excerpt": "The legendary financier Bill Gross holds bitcoin after having loudly criticized popular crypto.",
            "summary": "Bitcoin prices are not in great shape. Many investors and observers are wondering whether the top cryptocurrency by market value will soon return to its highs posted last November or if has left for a period of decline known as crypto winter. Well, if bitcoin is now prompting everyone to agree one of aspect of the cryptocurrency, it is its reputation. For the past few weeks bitcoin has been scoring victories on this front. Crypto is no longer seen in a bad light by the Biden administration in view of the presidential executive order that advises federal agencies/regulators not to stifle innovation.",
            "rights": "thestreet.com",
            "rank": 1376,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Luc Olinga"
            ],
            "media": "https://www.thestreet.com/.image/t_share/MTY4NjUxNjg5MzA4NTMwNTgz/allianz-shares-gain-after-pimco-reaches-agreement-with-bill-gross-over-2014-departure.png",
            "is_opinion": false,
            "twitter_account": "@thestreet",
            "_score": 9.0392475,
            "_id": "770e9e673469d14e3168dd14a0cf980a"
        },
        {
            "title": "Bitcoin Evangelist Saylor Tells Economists Why They're Wrong",
            "author": "Crystal Kim",
            "published_date": "2022-03-14 20:42:33",
            "published_date_precision": "full",
            "link": "http://www.bnnbloomberg.ca/bitcoin-evangelist-saylor-tells-economists-why-they-re-wrong-1.1737531",
            "clean_url": "bnnbloomberg.ca",
            "excerpt": "Michael Saylor, chief executive of enterprise software maker MicroStrategy Inc. and noted Bitcoin proselytizer, spoke to dozens of members of the Economic Club of New York on Monday about the merits…",
            "summary": "(Bloomberg) -- Michael Saylor, chief executive of enterprise software maker MicroStrategy Inc. and noted Bitcoin proselytizer, spoke to dozens of members of the Economic Club of New York on Monday about the merits of the world's largest digital asset, especially in the face of sharply rising inflation.Most mainstream economists have been slow to embrace Bitcoin, questioning the claims of advocates that the cryptocurrency serves as a store of value as well as an inflation hedge. The software entrepreneur explained how when the company was faced with the 'fast death' that the technology industry promised, the 'slow death' that expanding monetary supply presented, and taking a risk with Bitcoin, he chose the latter, because of the property-like values that the cryptocurrency exhibited.",
            "rights": null,
            "rank": 4758,
            "topic": "tech",
            "country": "CA",
            "language": "en",
            "authors": [
                "Bloomberg News"
            ],
            "media": "http://www.bnnbloomberg.ca/polopoly_fs/1.1737532!/fileimage/httpImage/image.jpg_gen/derivatives/landscape_620/michael-saylor.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.034119,
            "_id": "06e7f6edb95adb81323a6afcecd10074"
        },
        {
            "title": "$20M In Bitcoin Was Just Transferred Onto Gemini",
            "author": "Benzinga Insights",
            "published_date": "2022-03-14 17:02:21",
            "published_date_precision": "full",
            "link": "https://www.benzinga.com/markets/cryptocurrency/22/03/26126961/20m-in-bitcoin-was-just-transferred-onto-gemini",
            "clean_url": "benzinga.com",
            "excerpt": "What happened: An anonymous cryptocurrency wallet holding $20,872,460 of Bitcoin (CRYPTO:",
            "summary": "What happened: An anonymous cryptocurrency wallet holding $20,872,460 of Bitcoin (CRYPTO: BTC) just transferred their funds onto Gemini. The bitcoin wallet address tied to this transfer has been identified as:\nbc1q7xa6hs9v83876qt6vwk8ycpzqs2yayv3utvctz\nYou can view more details about the transaction here.\nWhy it matters: Cryptocurrency transfers from wallets to exchanges is typically a bearish signal. Most high networth cryptocurrency traders hold their funds on a hardware wallet, as these devices offer better security than cryptocurrency exchanges.",
            "rights": "benzinga.com",
            "rank": 2282,
            "topic": "finance",
            "country": "US",
            "language": "en",
            "authors": [
                "Benzinga Insights"
            ],
            "media": "https://cdn2.benzinga.com/files/imagecache/og_image_social_share_1200x630/images/story/2022/btc_whale_image_179.png?width=720",
            "is_opinion": false,
            "twitter_account": "@benzinga",
            "_score": 9.028289,
            "_id": "68512f033e6d6745db04b53d9d35eed5"
        },
        {
            "title": "Buy Crypto with Low Fees, Some Top Choices",
            "author": "Buy Crypto With Low Fees",
            "published_date": "2022-03-08 11:33:08",
            "published_date_precision": "full",
            "link": "https://www.heraldscotland.com/news/19976890.buy-crypto-low-fees-top-choices",
            "clean_url": "heraldscotland.com",
            "excerpt": "With Bitcoin now one of the best-performing assets in the financial arena, many people in the UK are looking to invest in this digital currency.",
            "summary": "With Bitcoin now one of the best-performing assets in the financial arena, many people in the UK are looking to invest in this digital currency. \n The good news is that the process takes less than five minutes when using a top-rated online broker that supports UK debit/credit cards and e-wallets.  \n\n In this article, we'll show you how to buy Bitcoin in the UK with an FCA-regulated broker that charges super-low fees. \n\n Where to Buy Bitcoin UK - Quick Steps\n\n Follow the quickfire guide below to learn how to buy Bitcoin in the UK at eToro - an FCA-regulated broker that supports plenty of convenient payment methods.",
            "rights": "heraldscotland.com",
            "rank": 3782,
            "topic": "news",
            "country": "GB",
            "language": "en",
            "authors": [
                "Buy Crypto With Low Fees",
                "Some Top Choices"
            ],
            "media": "https://www.heraldscotland.com/resources/images/13553528/",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.02273,
            "_id": "cf8452343324d4e50539d6a33af94424"
        },
        {
            "title": "Mama Bitcoin: Fishing for female empowerment with crypto in West Africa",
            "author": "Cointelegraph By Joseph Hall",
            "published_date": "2022-03-08 11:21:51",
            "published_date_precision": "full",
            "link": "https://cointelegraph.com/news/mama-bitcoin-fishing-for-female-empowerment-with-crypto-in-west-africa",
            "clean_url": "cointelegraph.com",
            "excerpt": "Celebrating the fascinating story of a young Senegalese woman who fell down the Bitcoin rabbit hole after MLM schemes and failures to finance a bakery.",
            "summary": "Mama Bitcoin is the pseudonym claimed by a young Senegalese Bitcoiner called Bineta. Her business, Bleu comme la mer, was the first retailer in Senegal (and possibly West Africa) to accept crypto as payment. She's also the first generation of her family to read and write proficiently. The name Mama Bitcoin takes inspiration from the initials of her name, while the 'mama' not only reflects her motherly instincts but serves to inspire other women in West Africa to get into blockchain technology and Bitcoin (BTC).",
            "rights": "cointelegraph.com",
            "rank": 1910,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Cointelegraph By Joseph Hall"
            ],
            "media": "https://images.cointelegraph.com/images/1200_aHR0cHM6Ly9zMy5jb2ludGVsZWdyYXBoLmNvbS91cGxvYWRzLzIwMjItMDMvZDEyODRiMjUtMmMzNC00OGZmLTkzZTAtYWQwOTM4YTU5N2EzLmpwZw==.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.01948,
            "_id": "8bdbf57852e8cfd12b008f90acb3742c"
        },
        {
            "title": "Why Isn't Bitcoin Booming?",
            "author": "EditorDavid",
            "published_date": "2022-03-12 18:34:00",
            "published_date_precision": "full",
            "link": "https://news.slashdot.org/story/22/03/12/0541251/why-isnt-bitcoin-booming",
            "clean_url": "slashdot.org",
            "excerpt": "\"Bitcoin was seen by many of its libertarian-leaning fans as a kind of doomsday insurance,\" argues a columnist in the New York Times, \"a form of 'digital gold' that would be a source of stability as…",
            "summary": "\"Bitcoin was seen by many of its libertarian-leaning fans as a kind of doomsday insurance,\" argues a columnist in the New York Times, \"a form of 'digital gold' that would be a source of stability as the world grew more chaotic and unpredictable.... \"But Bitcoin hasn't boomed.... Bitcoin prices are down 10 percent in the past month, and Ether, the second most popular crypto coin, is down roughly 15 percent.Day-to-day usage of cryptocurrencies isn't picking up the way you'd expect, either. Bitcoin trading volume rose after Russia invaded Ukraine, but it has remained relatively flat since, suggesting that people aren't rushing to trade their rubles and hryvnia (Ukraine's currency) for digital currencies.",
            "rights": "Copyright 1997-2016, SlashdotMedia. All Rights Reserved.",
            "rank": 551,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "EditorDavid"
            ],
            "media": "https://a.fsdn.com/sd/topics/bitcoin_64.png",
            "is_opinion": false,
            "twitter_account": "@slashdot",
            "_score": 9.008048,
            "_id": "849add2de3996f576ba7d55272999bb2"
        },
        {
            "title": "Crypto news: EU scraps PoW ban proposal following backlash",
            "author": "/u/sandygws",
            "published_date": "2022-03-14 13:11:46",
            "published_date_precision": "full",
            "link": "https://www.reddit.com/r/Bitcoin/comments/tdx73m/crypto_news_eu_scraps_pow_ban_proposal_following",
            "clean_url": "reddit.com",
            "excerpt": "submitted by /u/sandygws [link] [comments]",
            "summary": "Bitcoin is the currency of the Internet: a distributed, worldwide, decentralized digital money. Unlike traditional currencies such as dollars, bitcoins are issued and managed without any central authority whatsoever: there is no government, company, or bank in charge of Bitcoin. As such, it is more resistant to wild inflation and corrupt banks. With Bitcoin, you can be your own bank.",
            "rights": "reddit.com",
            "rank": 38,
            "topic": "finance",
            "country": "US",
            "language": "en",
            "authors": [
                "/u/sandygws"
            ],
            "media": "https://external-preview.redd.it/TF8rGKnvKxVuByCw7cTQlzX9FOdBHYh4hvisZc9iPLo.jpg?auto=webp&s=0c1a9ed1e5166e4cd6aabda8a05b7d78e318bd88",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 9.003705,
            "_id": "b12c523125e1bbbef3d0f93ad14cb724"
        },
        {
            "title": "Elon Musk says won't sell his Bitcoin, Ethereum, Doge against rising inflation backdrop",
            "author": "Justin Low",
            "published_date": "2022-03-14 04:14:45",
            "published_date_precision": "full",
            "link": "https://www.forexlive.com/Cryptocurrency/elon-musk-says-wont-sell-his-bitcoin-ethereum-doge-against-rising-inflation-backdrop-20220314",
            "clean_url": "forexlive.com",
            "excerpt": "Another tweet by Elon Musk",
            "summary": "BTC Slight jump in crypto assets on the tweet. He says that:\"As a general principle, for those looking for advice from this thread, it is generally better to own physical things like a home or stock in companies you think make good products, than dollars when inflation is high. I still own & won't sell my Bitcoin, Ethereum or Doge fwiw.\" He's responding to comments from an earlier tweet himself regarding what is the \"probably inflation rate\" in the years ahead.ETH is up 1% on the day now to just above $2,600 with  Bitcoin  Bitcoin Bitcoin is the largest and world's first digital currency launched back in 2009 by the entity, Satoshi Nakamoto.",
            "rights": "Copyright 2022 Forexlive.com",
            "rank": 32326,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Justin Low"
            ],
            "media": "https://images.forexlive.com/images/ETH_id_fb5da14b-8be4-4131-a75a-6d66a7152ff0_original.jpg",
            "is_opinion": false,
            "twitter_account": "@ForexLive",
            "_score": 8.993451,
            "_id": "c4cdbabec85ef2e95e5822d2c7a7b4ed"
        },
        {
            "title": "Two years since the COVID-19 crash: 5 things to know in Bitcoin this week",
            "author": "Cointelegraph By William Suberg",
            "published_date": "2022-03-14 07:54:47",
            "published_date_precision": "full",
            "link": "https://cointelegraph.com/news/two-years-since-the-covid-crash-5-things-to-know-in-bitcoin-this-week",
            "clean_url": "cointelegraph.com",
            "excerpt": "Bitcoin gears up for a frenetic macro week of BTC price triggers.",
            "summary": "It‘s been two years since BTC/USD crashed to $3,600 and it is trading over ten times higher — but clouds, as ever, are looming large. Markets News Bitcoin (BTC) starts a new week struggling to preserve support as key macro changes appear on the horizon.In what could turn out to be a crucial week for Bitcoin and altcoins' relationship with traditional assets, the United States Federal Reserve is set to be the main talking point for hodlers.Amid an atmosphere of still rampant inflation, quantitative easing still ongoing and geopolitical turmoil focused on Europe, there is plenty of uncertainty in the air, no matter what the trade.",
            "rights": "cointelegraph.com",
            "rank": 1910,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Cointelegraph By William Suberg"
            ],
            "media": "https://images.cointelegraph.com/images/1200_aHR0cHM6Ly9zMy5jb2ludGVsZWdyYXBoLmNvbS91cGxvYWRzLzIwMjItMDMvY2NkNGU5YzgtMGI3Zi00YjI3LWIzZTEtM2NiOGFlMWIzODNkLmpwZw==.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": 8.992133,
            "_id": "2c35ce5a5eb98566d28874b9fcafbee8"
        },
        {
            "title": "Unearthing the Bitcoin Tapes",
            "author": null,
            "published_date": "2022-03-14 13:00:00",
            "published_date_precision": "full",
            "link": "https://www.vice.com/en/article/xgdkqz/unearthing-the-bitcoin-tapes",
            "clean_url": "vice.com",
            "excerpt": "Nine years later, we're finally publishing footage from one of the first major Bitcoin conferences.",
            "summary": "Every so often, someone at Motherboard (or a few of my former colleagues who have since left Motherboard) will say something like 'We should do something with that old Bitcoin footage.' I always agreed, and then started on some email adventure. I heard about the Bitcoin tapes soon after I started at Motherboard in 2013, which, according to my calculations, was 'a long time ago.' We sent a team of people to the Bitcoin 2013 conference in San Jose, which was one of the first major Bitcoin conferences.",
            "rights": "vice.com",
            "rank": 277,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [],
            "media": "https://video-images.vice.com/articles/622bb0c6364e100096a972ed/lede/1647030631761-screen-shot-2022-03-11-at-33012-pm.png?image-resize-opts=Y3JvcD0wLjg5NzN4dzowLjk5ODl4aDswLjAxNTd4dywwLjAwMTF4aCZyZXNpemU9MTIwMDoqJnJlc2l6ZT0xMjAwOio",
            "is_opinion": false,
            "twitter_account": "@vice",
            "_score": 8.991633,
            "_id": "d08e47f3c3991644099c900059479e35"
        },
        {
            "title": "‘Bitcoin To $100,000 In Two Years'—A Former White House Press Secretary Issued A Huge Crypto Price Prediction",
            "author": "Billy Bambrough",
            "published_date": "2022-03-09 00:45:03",
            "published_date_precision": "full",
            "link": "https://www.forbes.com/sites/billybambrough/2022/03/08/bitcoin-to-100000-in-two-years-a-former-white-house-press-secretary-issued-a-huge-crypto-price-prediction",
            "clean_url": "forbes.com",
            "excerpt": "Anthony Scaramucci, Donald Trump's short-lived White House press secretary who launched a bitcoin fund last year, has issued a bold bitcoin price prediction...",
            "summary": "Bitcoin and cryptocurrency prices have failed to rally in the face of the escalating Russian invasion of Ukraine, even as the gold price hits an all-time high. Subscribe now to Forbes' CryptoAsset & Blockchain Advisor and successfully navigate the latest crypto price crash The bitcoin price has lost almost 20% since the beginning of 2022 as stock markets crater in face of looming Federal Reserve interest rate hikes. Now, Anthony Scaramucci, Donald Trump's short-lived White House press secretary who launched a bitcoin fund last year, has issued a bold bitcoin price prediction, forecasting bitcoin will hit $100,000 within two years—and ultimately climb to $500,000.",
            "rights": "forbes.com",
            "rank": 51,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Billy Bambrough",
                "Senior Contributor"
            ],
            "media": "https://imageio.forbes.com/specials-images/imageserve/60585d3d60d1b3bd4a7ca8ff/0x0.jpg?format=jpg&width=1200&fit=bounds",
            "is_opinion": false,
            "twitter_account": "@forbes",
            "_score": 8.990757,
            "_id": "aaf3add95f1af536bdf334c49df86302"
        },
        {
            "title": "Malta's Michelin Chef Now Accepts Bitcoin and Lightning Payments",
            "author": null,
            "published_date": "2022-03-14 14:31:00",
            "published_date_precision": "full",
            "link": "https://www.investing.com/news/cryptocurrency-news/maltas-michelin-chef-now-accepts-bitcoin-and-lightning-payments-2784141",
            "clean_url": "investing.com",
            "excerpt": "Malta's Michelin Chef Now Accepts Bitcoin and Lightning Payments",
            "summary": "© Reuters. Malta's Michelin Chef Now Accepts Bitcoin and Lightning Payments\n\n\n Michelin (PA:) chef Marvin Gauci accepts and Lightning in his restaurants.\nChef Marvin aims to earn the first Bitcoin restaurant award in Malta – the Satoshi star.\nCryptocurrency managed to permeate another aspect of Malta's lifestyle: fine dining.\nMarvin Gauci is a restaurant chef who has an extreme streak — a characteristic that helped him to earn a Michelin star. He considers himself fortunate to own one of the few restaurants on the small Island to have gotten the prestigious award.",
            "rights": "investing.com",
            "rank": 1732,
            "topic": "news",
            "country": "ES",
            "language": "en",
            "authors": [],
            "media": "https://i-invdn-com.investing.com/news/LYNXMPEA74100_L.jpg",
            "is_opinion": false,
            "twitter_account": "@investingcom",
            "_score": 8.988087,
            "_id": "e776f3512335e9ac02847da1c3619a89"
        },
        {
            "title": "Better understand Bitcoin with this free online course on Udemy",
            "author": "Joseph Green",
            "published_date": "2022-03-10 04:55:00",
            "published_date_precision": "full",
            "link": "https://mashable.com/uk/deals/best-free-bitcoin-course",
            "clean_url": "mashable.com",
            "excerpt": "Build and grow your wealth.",
            "summary": "Deal pricing and availability subject to change after time of publication.\n\nFREE BITCOIN COURSE: The Bitcoin University: Build and Grow Your Wealth with Bitcoin course is available for free on Udemy with the voucher code 51FBEE6519A60E831996.The world of cryptocurrencies is complex. There's definitely a fairly steep learning curve with the technology, but once you better understand how things work, you can build and grow your personal wealth. We're not making any promises here, but if you're looking to profit from crypto, you should check out the Bitcoin University: Build and Grow Your Wealth with Bitcoin course.",
            "rights": "Copyright 2022 Mashable, Inc. All Rights Reserved.",
            "rank": 259,
            "topic": "news",
            "country": "US",
            "language": "en",
            "authors": [
                "Joseph Green"
            ],
            "media": "https://helios-i.mashable.com/imagery/articles/0291BUYNLkFhluweruJGyxz/hero-image.fill.size_1200x675.v1646826557.jpg",
            "is_opinion": false,
            "twitter_account": "@mashable",
            "_score": 8.986525,
            "_id": "cb12a88e5e6e16e8ccf66368b8617b2a"
        }
    ],
    "user_input": {
        "q": "Bitcoin",
        "search_in": [
            "title_summary_en"
        ],
        "lang": [
            "en"
        ],
        "not_lang": null,
        "countries": null,
        "not_countries": null,
        "from": "2022-03-08 00:00:00",
        "to": null,
        "ranked_only": "True",
        "from_rank": null,
        "to_rank": null,
        "sort_by": "relevancy",
        "page": 1,
        "size": 50,
        "sources": null,
        "not_sources": null,
        "topic": null,
        "published_date_precision": null
    }
}]