const categories = {
    "City": [
        'Mumbai', 'Delhi',
        'Chennai', 'Pune',
        'Nashik', 'Bangalore',
        'Hydrabad', 'Luckhnow',
        'Kolkata', 'Jaipur'
    ],
    'University': [
        'Visvesvaraya Technological University, Belagavi',
        'Dr Vishwanath Karad MIT World Peace University, Pune',
        'University of Mumbai, Mumbai',
        'Amrita Vishwa Vidyapeetham, Coimbatore',
        'Birla Institute of Technology and Science, Pilani',
        'Jawaharlal Nehru Technological University, Hyderabad',
        'Andhra University, Visakhapatnam',
        'Vellore Institute of Technology, Vellore',
        'Savitribai Phule Pune University, Pune',
        'Osmania University, Hyderabad',
        'Dr APJ Abdul Kalam Technical University, Lucknow',
        'Maulana Abul Kalam Azad University of Technology, Kolkata',
        'Dr Babasaheb Ambedkar Marathwada University, Aurangabad',
        'Bharati Vidyapeeth, Pune',
        'Jawaharlal Nehru Technological University, Kakinada',
        'Sri Venkateswara University, Tirupati',
        'Gujarat Technological University, Ahmedabad',
        'APJ Abdul Kalam Technological University, Thiruvananthapuram',
        'Guru Gobind Singh Indraprastha University, Delhi',
        'SRM Institute of Science and Technology, Chennai',
        ''
    ],
    'State': [
        'Maharashtra',
        'Delhi',
        'Jharkhand',
        'Telangana',
        'Karnataka',
        'Uttar Pradesh',
        'Punjab',
        'Gujarat',
        'Tamil Nadu',
        'West Bengal',
        'Kerala',
        'Haryana',
        'Rajasthan',
        'Madhya Pradesh',
        'Assam',
        'Andhra Pradesh',
        'Chandigarh',
        'Chhattisgarh',
        'Odisha',
        'Bihar',
        'Himachal Pradesh',
        'Manipur',
        'Uttarakhand',
        'Tripura',
        'Goa',
        'Jammu and Kashmir',
        'Puducherry',
        'Meghalaya',
        'Arunachal Pradesh',
        'Nagaland',
        'Mizoram',
        'Sikkim',
        'name',
        'Andaman and Nicobar Islands',
        'Dadra and Nagar Haveli',
        'MBA Collaboration with University of Warwick UK'
        ],
    "Courses":["B.Tech","M.Tech","B.Sc","BA","MA","MBA","MBBS","Diploma","LLB", "B.Com"]
}
module.exports = categories